version: '3.6'
services:
  service:
    build:
      context: .
      target: service
    image: ghcr.io/tao-radar/not-tao-stats:main
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://posterbot-redis:6379/0
      - NETWORK=finney
    networks:
      - posterbot_default
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  worker:
    build:
      context: .
      target: service
    image: ghcr.io/tao-radar/not-tao-stats:main
    command: python -m openapi_server.worker
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://posterbot-redis:6379/0
      - NETWORK=finney
    networks:
      - posterbot_default
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_INCLUDE_STOPPED=true
    restart: unless-stopped

networks:
  posterbot_default:
    external: true
