# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import traceback
import logging

from fastapi import FastAPI, Request, status
from fastapi.responses import JSONResponse

from openapi_server.apis.account_api import router as AccountApiRouter
from openapi_server.apis.accounting_api import router as AccountingApiRouter
from openapi_server.apis.block_api import router as BlockApiRouter
from openapi_server.apis.call_api import router as CallApiRouter
from openapi_server.apis.coingecko_api import router as CoingeckoApiRouter
from openapi_server.apis.coldkey_swap_api import router as ColdkeySwapApiRouter
from openapi_server.apis.delegation_api import router as DelegationApiRouter
from openapi_server.apis.dev_activity_api import router as DevActivityApiRouter
from openapi_server.apis.dtao_api import router as DtaoApiRouter
from openapi_server.apis.erc20_api import router as Erc20ApiRouter
from openapi_server.apis.event_api import router as EventApiRouter
from openapi_server.apis.evm_api import router as EvmApiRouter
from openapi_server.apis.exchange_api import router as ExchangeApiRouter
from openapi_server.apis.extrinsic_api import router as ExtrinsicApiRouter
from openapi_server.apis.hotkey_api import router as HotkeyApiRouter
from openapi_server.apis.identity_api import router as IdentityApiRouter
from openapi_server.apis.liquidity_api import router as LiquidityApiRouter
from openapi_server.apis.live_api import router as LiveApiRouter
from openapi_server.apis.metagraph_api import router as MetagraphApiRouter
from openapi_server.apis.miner_api import router as MinerApiRouter
from openapi_server.apis.network_parameter_api import router as NetworkParameterApiRouter
from openapi_server.apis.neuron_api import router as NeuronApiRouter
from openapi_server.apis.otc_api import router as OtcApiRouter
from openapi_server.apis.pool_api import router as PoolApiRouter
from openapi_server.apis.price_api import router as PriceApiRouter
from openapi_server.apis.proxy_call_api import router as ProxyCallApiRouter
from openapi_server.apis.rpc_api import router as RpcApiRouter
from openapi_server.apis.runtime_version_api import router as RuntimeVersionApiRouter
from openapi_server.apis.stake_api import router as StakeApiRouter
from openapi_server.apis.stake_balance_api import router as StakeBalanceApiRouter
from openapi_server.apis.stats_api import router as StatsApiRouter
from openapi_server.apis.status_api import router as StatusApiRouter
from openapi_server.apis.subnet_api import router as SubnetApiRouter
from openapi_server.apis.trades_api import router as TradesApiRouter
from openapi_server.apis.transfer_api import router as TransferApiRouter
from openapi_server.apis.validator_api import router as ValidatorApiRouter

app = FastAPI(
    title="taostats",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="1.8.51",
)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    """Global exception handler that logs full tracebacks for all exceptions."""
    logger.error(
        f"Unhandled exception: {exc}\n"
        f"Request: {request.method} {request.url}\n"
        f"Traceback:\n{''.join(traceback.format_exception(type(exc), exc, exc.__traceback__))}",
        exc_info=True
    )
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "Internal server error"}
    )

app.include_router(AccountApiRouter)
app.include_router(AccountingApiRouter)
app.include_router(BlockApiRouter)
app.include_router(CallApiRouter)
app.include_router(CoingeckoApiRouter)
app.include_router(ColdkeySwapApiRouter)
app.include_router(DelegationApiRouter)
app.include_router(DevActivityApiRouter)
app.include_router(DtaoApiRouter)
app.include_router(Erc20ApiRouter)
app.include_router(EventApiRouter)
app.include_router(EvmApiRouter)
app.include_router(ExchangeApiRouter)
app.include_router(ExtrinsicApiRouter)
app.include_router(HotkeyApiRouter)
app.include_router(IdentityApiRouter)
app.include_router(LiquidityApiRouter)
app.include_router(LiveApiRouter)
app.include_router(MetagraphApiRouter)
app.include_router(MinerApiRouter)
app.include_router(NetworkParameterApiRouter)
app.include_router(NeuronApiRouter)
app.include_router(OtcApiRouter)
app.include_router(PoolApiRouter)
app.include_router(PriceApiRouter)
app.include_router(ProxyCallApiRouter)
app.include_router(RpcApiRouter)
app.include_router(RuntimeVersionApiRouter)
app.include_router(StakeApiRouter)
app.include_router(StakeBalanceApiRouter)
app.include_router(StatsApiRouter)
app.include_router(StatusApiRouter)
app.include_router(SubnetApiRouter)
app.include_router(TradesApiRouter)
app.include_router(TransferApiRouter)
app.include_router(ValidatorApiRouter)
