# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.coldkey_swap_item import ColdkeySwapItem
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccountHistoryItem(BaseModel):
    """
    AccountHistoryItem
    """ # noqa: E501
    address: Key
    balance_free: StrictStr
    balance_liquidity: StrictStr
    balance_reserved: StrictStr
    balance_staked: StrictStr
    balance_staked_alpha_as_tao: StrictStr
    balance_staked_root: StrictStr
    balance_total: StrictStr
    block_number: int
    coldkey_swap: Optional[ColdkeySwapItem] = None
    created_on_date: date
    created_on_network: StrictStr
    network: StrictStr
    rank: int
    root_claim_type: StrictStr
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["address", "balance_free", "balance_liquidity", "balance_reserved", "balance_staked", "balance_staked_alpha_as_tao", "balance_staked_root", "balance_total", "block_number", "coldkey_swap", "created_on_date", "created_on_network", "network", "rank", "root_claim_type", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountHistoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of coldkey_swap
        if self.coldkey_swap:
            _dict['coldkey_swap'] = self.coldkey_swap.to_dict()
        # set to None if coldkey_swap (nullable) is None
        # and model_fields_set contains the field
        if self.coldkey_swap is None and "coldkey_swap" in self.model_fields_set:
            _dict['coldkey_swap'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccountHistoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": Key.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "balance_free": obj.get("balance_free"),
            "balance_liquidity": obj.get("balance_liquidity"),
            "balance_reserved": obj.get("balance_reserved"),
            "balance_staked": obj.get("balance_staked"),
            "balance_staked_alpha_as_tao": obj.get("balance_staked_alpha_as_tao"),
            "balance_staked_root": obj.get("balance_staked_root"),
            "balance_total": obj.get("balance_total"),
            "block_number": obj.get("block_number"),
            "coldkey_swap": ColdkeySwapItem.from_dict(obj.get("coldkey_swap")) if obj.get("coldkey_swap") is not None else None,
            "created_on_date": obj.get("created_on_date"),
            "created_on_network": obj.get("created_on_network"),
            "network": obj.get("network"),
            "rank": obj.get("rank"),
            "root_claim_type": obj.get("root_claim_type"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


