# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.stake_balance_item import StakeBalanceItem
from openapi_server.models.subnet_neuron_registration_item import SubnetNeuronRegistrationItem
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccountingItem(BaseModel):
    """
    AccountingItem
    """ # noqa: E501
    income: StrictStr
    neuron_registration_cost: StrictStr
    neuron_registrations: List[SubnetNeuronRegistrationItem]
    stake_balances: List[StakeBalanceItem]
    __properties: ClassVar[List[str]] = ["income", "neuron_registration_cost", "neuron_registrations", "stake_balances"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountingItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in neuron_registrations (list)
        _items = []
        if self.neuron_registrations:
            for _item in self.neuron_registrations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['neuron_registrations'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in stake_balances (list)
        _items = []
        if self.stake_balances:
            for _item in self.stake_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict['stake_balances'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccountingItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "income": obj.get("income"),
            "neuron_registration_cost": obj.get("neuron_registration_cost"),
            "neuron_registrations": [SubnetNeuronRegistrationItem.from_dict(_item) for _item in obj.get("neuron_registrations")] if obj.get("neuron_registrations") is not None else None,
            "stake_balances": [StakeBalanceItem.from_dict(_item) for _item in obj.get("stake_balances")] if obj.get("stake_balances") is not None else None
        })
        return _obj


