# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.account_order import AccountOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccountRequest(BaseModel):
    """
    AccountRequest
    """ # noqa: E501
    address: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    balance_free_max: Optional[StrictStr] = None
    balance_free_min: Optional[StrictStr] = None
    balance_staked_alpha_as_tao_max: Optional[StrictStr] = None
    balance_staked_alpha_as_tao_min: Optional[StrictStr] = None
    balance_staked_max: Optional[StrictStr] = None
    balance_staked_min: Optional[StrictStr] = None
    balance_staked_root_max: Optional[StrictStr] = None
    balance_staked_root_min: Optional[StrictStr] = None
    balance_total_max: Optional[StrictStr] = None
    balance_total_min: Optional[StrictStr] = None
    created_on_network: Optional[StrictStr] = Field(default=None, description="finney, nakamoto, kusanagi")
    created_on_timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    created_on_timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    limit: Optional[int] = None
    order: Optional[AccountOrder] = None
    page: Optional[int] = None
    rank: Optional[int] = None
    __properties: ClassVar[List[str]] = ["address", "balance_free_max", "balance_free_min", "balance_staked_alpha_as_tao_max", "balance_staked_alpha_as_tao_min", "balance_staked_max", "balance_staked_min", "balance_staked_root_max", "balance_staked_root_min", "balance_total_max", "balance_total_min", "created_on_network", "created_on_timestamp_end", "created_on_timestamp_start", "limit", "order", "page", "rank"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if balance_free_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_free_max is None and "balance_free_max" in self.model_fields_set:
            _dict['balance_free_max'] = None

        # set to None if balance_free_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_free_min is None and "balance_free_min" in self.model_fields_set:
            _dict['balance_free_min'] = None

        # set to None if balance_staked_alpha_as_tao_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_alpha_as_tao_max is None and "balance_staked_alpha_as_tao_max" in self.model_fields_set:
            _dict['balance_staked_alpha_as_tao_max'] = None

        # set to None if balance_staked_alpha_as_tao_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_alpha_as_tao_min is None and "balance_staked_alpha_as_tao_min" in self.model_fields_set:
            _dict['balance_staked_alpha_as_tao_min'] = None

        # set to None if balance_staked_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_max is None and "balance_staked_max" in self.model_fields_set:
            _dict['balance_staked_max'] = None

        # set to None if balance_staked_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_min is None and "balance_staked_min" in self.model_fields_set:
            _dict['balance_staked_min'] = None

        # set to None if balance_staked_root_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_root_max is None and "balance_staked_root_max" in self.model_fields_set:
            _dict['balance_staked_root_max'] = None

        # set to None if balance_staked_root_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_staked_root_min is None and "balance_staked_root_min" in self.model_fields_set:
            _dict['balance_staked_root_min'] = None

        # set to None if balance_total_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_total_max is None and "balance_total_max" in self.model_fields_set:
            _dict['balance_total_max'] = None

        # set to None if balance_total_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_total_min is None and "balance_total_min" in self.model_fields_set:
            _dict['balance_total_min'] = None

        # set to None if created_on_network (nullable) is None
        # and model_fields_set contains the field
        if self.created_on_network is None and "created_on_network" in self.model_fields_set:
            _dict['created_on_network'] = None

        # set to None if created_on_timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.created_on_timestamp_end is None and "created_on_timestamp_end" in self.model_fields_set:
            _dict['created_on_timestamp_end'] = None

        # set to None if created_on_timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.created_on_timestamp_start is None and "created_on_timestamp_start" in self.model_fields_set:
            _dict['created_on_timestamp_start'] = None

        # set to None if rank (nullable) is None
        # and model_fields_set contains the field
        if self.rank is None and "rank" in self.model_fields_set:
            _dict['rank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccountRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "balance_free_max": obj.get("balance_free_max"),
            "balance_free_min": obj.get("balance_free_min"),
            "balance_staked_alpha_as_tao_max": obj.get("balance_staked_alpha_as_tao_max"),
            "balance_staked_alpha_as_tao_min": obj.get("balance_staked_alpha_as_tao_min"),
            "balance_staked_max": obj.get("balance_staked_max"),
            "balance_staked_min": obj.get("balance_staked_min"),
            "balance_staked_root_max": obj.get("balance_staked_root_max"),
            "balance_staked_root_min": obj.get("balance_staked_root_min"),
            "balance_total_max": obj.get("balance_total_max"),
            "balance_total_min": obj.get("balance_total_min"),
            "created_on_network": obj.get("created_on_network"),
            "created_on_timestamp_end": obj.get("created_on_timestamp_end"),
            "created_on_timestamp_start": obj.get("created_on_timestamp_start"),
            "limit": obj.get("limit"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "rank": obj.get("rank")
        })
        return _obj


