# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.network import Network
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class AccountingRequest(BaseModel):
    """
    AccountingRequest
    """ # noqa: E501
    coldkey: StrictStr = Field(description="SS58 or hex format")
    date_end: date = Field(description="End of date range in YYYY-MM-DD format (inclusive)")
    date_start: date = Field(description="Start of date range in YYYY-MM-DD format (inclusive)")
    hotkey: Optional[StrictStr] = None
    network: Optional[Network] = None
    __properties: ClassVar[List[str]] = ["coldkey", "date_end", "date_start", "hotkey", "network"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of AccountingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coldkey": obj.get("coldkey"),
            "date_end": obj.get("date_end"),
            "date_start": obj.get("date_start"),
            "hotkey": obj.get("hotkey"),
            "network": obj.get("network")
        })
        return _obj


