# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BlockItem(BaseModel):
    """
    BlockItem
    """ # noqa: E501
    block_number: int
    calls_count: int
    events_count: int
    extrinsics_count: int
    extrinsics_root: StrictStr
    hash: StrictStr
    impl_name: StrictStr
    impl_version: int
    parent_hash: StrictStr
    spec_name: StrictStr
    spec_version: int
    state_root: StrictStr
    timestamp: datetime
    validator: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["block_number", "calls_count", "events_count", "extrinsics_count", "extrinsics_root", "hash", "impl_name", "impl_version", "parent_hash", "spec_name", "spec_version", "state_root", "timestamp", "validator"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BlockItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if validator (nullable) is None
        # and model_fields_set contains the field
        if self.validator is None and "validator" in self.model_fields_set:
            _dict['validator'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BlockItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "calls_count": obj.get("calls_count"),
            "events_count": obj.get("events_count"),
            "extrinsics_count": obj.get("extrinsics_count"),
            "extrinsics_root": obj.get("extrinsics_root"),
            "hash": obj.get("hash"),
            "impl_name": obj.get("impl_name"),
            "impl_version": obj.get("impl_version"),
            "parent_hash": obj.get("parent_hash"),
            "spec_name": obj.get("spec_name"),
            "spec_version": obj.get("spec_version"),
            "state_root": obj.get("state_root"),
            "timestamp": obj.get("timestamp"),
            "validator": obj.get("validator")
        })
        return _obj


