# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CallItem(BaseModel):
    """
    CallItem
    """ # noqa: E501
    args: Optional[Any] = None
    block_number: int
    error: Optional[Any] = None
    extrinsic_id: StrictStr
    extrinsic_index: Optional[int] = None
    full_name: StrictStr
    id: StrictStr
    name: StrictStr
    origin: Optional[Any] = None
    origin_address: Optional[StrictStr] = None
    pallet: StrictStr
    parent_id: Optional[StrictStr] = None
    success: StrictBool
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["args", "block_number", "error", "extrinsic_id", "extrinsic_index", "full_name", "id", "name", "origin", "origin_address", "pallet", "parent_id", "success", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CallItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if args (nullable) is None
        # and model_fields_set contains the field
        if self.args is None and "args" in self.model_fields_set:
            _dict['args'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if extrinsic_index (nullable) is None
        # and model_fields_set contains the field
        if self.extrinsic_index is None and "extrinsic_index" in self.model_fields_set:
            _dict['extrinsic_index'] = None

        # set to None if origin (nullable) is None
        # and model_fields_set contains the field
        if self.origin is None and "origin" in self.model_fields_set:
            _dict['origin'] = None

        # set to None if origin_address (nullable) is None
        # and model_fields_set contains the field
        if self.origin_address is None and "origin_address" in self.model_fields_set:
            _dict['origin_address'] = None

        # set to None if parent_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_id is None and "parent_id" in self.model_fields_set:
            _dict['parent_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CallItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "args": obj.get("args"),
            "block_number": obj.get("block_number"),
            "error": obj.get("error"),
            "extrinsic_id": obj.get("extrinsic_id"),
            "extrinsic_index": obj.get("extrinsic_index"),
            "full_name": obj.get("full_name"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "origin": obj.get("origin"),
            "origin_address": obj.get("origin_address"),
            "pallet": obj.get("pallet"),
            "parent_id": obj.get("parent_id"),
            "success": obj.get("success"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


