# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.coin_gecko_block import CoinGeckoBlock
from openapi_server.models.coin_gecko_reserves import CoinGeckoReserves
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class CoinGeckoEvent(BaseModel):
    """
    CoinGeckoEvent
    """ # noqa: E501
    asset0_in: Optional[StrictStr] = Field(default=None, alias="asset0In")
    asset0_out: Optional[StrictStr] = Field(default=None, alias="asset0Out")
    asset1_in: Optional[StrictStr] = Field(default=None, alias="asset1In")
    asset1_out: Optional[StrictStr] = Field(default=None, alias="asset1Out")
    block: CoinGeckoBlock
    event_index: int = Field(alias="eventIndex")
    event_type: StrictStr = Field(alias="eventType")
    maker: StrictStr
    pair_id: StrictStr = Field(alias="pairId")
    price_native: StrictStr = Field(alias="priceNative")
    reserves: CoinGeckoReserves
    txn_id: StrictStr = Field(alias="txnId")
    txn_index: int = Field(alias="txnIndex")
    __properties: ClassVar[List[str]] = ["asset0In", "asset0Out", "asset1In", "asset1Out", "block", "eventIndex", "eventType", "maker", "pairId", "priceNative", "reserves", "txnId", "txnIndex"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CoinGeckoEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of block
        if self.block:
            _dict['block'] = self.block.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reserves
        if self.reserves:
            _dict['reserves'] = self.reserves.to_dict()
        # set to None if asset0_in (nullable) is None
        # and model_fields_set contains the field
        if self.asset0_in is None and "asset0_in" in self.model_fields_set:
            _dict['asset0In'] = None

        # set to None if asset0_out (nullable) is None
        # and model_fields_set contains the field
        if self.asset0_out is None and "asset0_out" in self.model_fields_set:
            _dict['asset0Out'] = None

        # set to None if asset1_in (nullable) is None
        # and model_fields_set contains the field
        if self.asset1_in is None and "asset1_in" in self.model_fields_set:
            _dict['asset1In'] = None

        # set to None if asset1_out (nullable) is None
        # and model_fields_set contains the field
        if self.asset1_out is None and "asset1_out" in self.model_fields_set:
            _dict['asset1Out'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of CoinGeckoEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asset0In": obj.get("asset0In"),
            "asset0Out": obj.get("asset0Out"),
            "asset1In": obj.get("asset1In"),
            "asset1Out": obj.get("asset1Out"),
            "block": CoinGeckoBlock.from_dict(obj.get("block")) if obj.get("block") is not None else None,
            "eventIndex": obj.get("eventIndex"),
            "eventType": obj.get("eventType"),
            "maker": obj.get("maker"),
            "pairId": obj.get("pairId"),
            "priceNative": obj.get("priceNative"),
            "reserves": CoinGeckoReserves.from_dict(obj.get("reserves")) if obj.get("reserves") is not None else None,
            "txnId": obj.get("txnId"),
            "txnIndex": obj.get("txnIndex")
        })
        return _obj


