# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ColdkeyReportItem(BaseModel):
    """
    ColdkeyReportItem
    """ # noqa: E501
    additional_data: Optional[StrictStr] = None
    block_number: int
    coldkey: StrictStr
    credit_amount: Optional[StrictStr] = None
    daily_income: Optional[StrictStr] = None
    daily_income_usd: Optional[StrictStr] = None
    var_date: Optional[date] = Field(default=None, alias="date")
    debit_amount: Optional[StrictStr] = None
    extrinsic_id: Optional[StrictStr] = None
    free_balance: Optional[StrictStr] = None
    locked_balance: Optional[StrictStr] = None
    network: StrictStr
    staked_balance: Optional[StrictStr] = None
    tao_price: Optional[StrictStr] = None
    timestamp: datetime
    total_balance: Optional[StrictStr] = None
    transaction_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["additional_data", "block_number", "coldkey", "credit_amount", "daily_income", "daily_income_usd", "date", "debit_amount", "extrinsic_id", "free_balance", "locked_balance", "network", "staked_balance", "tao_price", "timestamp", "total_balance", "transaction_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ColdkeyReportItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if additional_data (nullable) is None
        # and model_fields_set contains the field
        if self.additional_data is None and "additional_data" in self.model_fields_set:
            _dict['additional_data'] = None

        # set to None if credit_amount (nullable) is None
        # and model_fields_set contains the field
        if self.credit_amount is None and "credit_amount" in self.model_fields_set:
            _dict['credit_amount'] = None

        # set to None if daily_income (nullable) is None
        # and model_fields_set contains the field
        if self.daily_income is None and "daily_income" in self.model_fields_set:
            _dict['daily_income'] = None

        # set to None if daily_income_usd (nullable) is None
        # and model_fields_set contains the field
        if self.daily_income_usd is None and "daily_income_usd" in self.model_fields_set:
            _dict['daily_income_usd'] = None

        # set to None if var_date (nullable) is None
        # and model_fields_set contains the field
        if self.var_date is None and "var_date" in self.model_fields_set:
            _dict['date'] = None

        # set to None if debit_amount (nullable) is None
        # and model_fields_set contains the field
        if self.debit_amount is None and "debit_amount" in self.model_fields_set:
            _dict['debit_amount'] = None

        # set to None if extrinsic_id (nullable) is None
        # and model_fields_set contains the field
        if self.extrinsic_id is None and "extrinsic_id" in self.model_fields_set:
            _dict['extrinsic_id'] = None

        # set to None if free_balance (nullable) is None
        # and model_fields_set contains the field
        if self.free_balance is None and "free_balance" in self.model_fields_set:
            _dict['free_balance'] = None

        # set to None if locked_balance (nullable) is None
        # and model_fields_set contains the field
        if self.locked_balance is None and "locked_balance" in self.model_fields_set:
            _dict['locked_balance'] = None

        # set to None if staked_balance (nullable) is None
        # and model_fields_set contains the field
        if self.staked_balance is None and "staked_balance" in self.model_fields_set:
            _dict['staked_balance'] = None

        # set to None if tao_price (nullable) is None
        # and model_fields_set contains the field
        if self.tao_price is None and "tao_price" in self.model_fields_set:
            _dict['tao_price'] = None

        # set to None if total_balance (nullable) is None
        # and model_fields_set contains the field
        if self.total_balance is None and "total_balance" in self.model_fields_set:
            _dict['total_balance'] = None

        # set to None if transaction_type (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_type is None and "transaction_type" in self.model_fields_set:
            _dict['transaction_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ColdkeyReportItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additional_data": obj.get("additional_data"),
            "block_number": obj.get("block_number"),
            "coldkey": obj.get("coldkey"),
            "credit_amount": obj.get("credit_amount"),
            "daily_income": obj.get("daily_income"),
            "daily_income_usd": obj.get("daily_income_usd"),
            "date": obj.get("date"),
            "debit_amount": obj.get("debit_amount"),
            "extrinsic_id": obj.get("extrinsic_id"),
            "free_balance": obj.get("free_balance"),
            "locked_balance": obj.get("locked_balance"),
            "network": obj.get("network"),
            "staked_balance": obj.get("staked_balance"),
            "tao_price": obj.get("tao_price"),
            "timestamp": obj.get("timestamp"),
            "total_balance": obj.get("total_balance"),
            "transaction_type": obj.get("transaction_type")
        })
        return _obj


