# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.currency_code import CurrencyCode
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ConfigResponse(BaseModel):
    """
    ConfigResponse
    """ # noqa: E501
    currency_codes: List[CurrencyCode]
    exchanges: List[StrictStr]
    supported_resolutions: List[StrictStr]
    supports_group_request: StrictBool
    supports_marks: StrictBool
    supports_search: StrictBool
    supports_timescale_marks: StrictBool
    __properties: ClassVar[List[str]] = ["currency_codes", "exchanges", "supported_resolutions", "supports_group_request", "supports_marks", "supports_search", "supports_timescale_marks"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConfigResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in currency_codes (list)
        _items = []
        if self.currency_codes:
            for _item in self.currency_codes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['currency_codes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ConfigResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "currency_codes": [CurrencyCode.from_dict(_item) for _item in obj.get("currency_codes")] if obj.get("currency_codes") is not None else None,
            "exchanges": obj.get("exchanges"),
            "supported_resolutions": obj.get("supported_resolutions"),
            "supports_group_request": obj.get("supports_group_request"),
            "supports_marks": obj.get("supports_marks"),
            "supports_search": obj.get("supports_search"),
            "supports_timescale_marks": obj.get("supports_timescale_marks")
        })
        return _obj


