# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DelegationItem(BaseModel):
    """
    DelegationItem
    """ # noqa: E501
    action: StrictStr
    alpha: Optional[StrictStr] = None
    alpha_price_in_tao: Optional[StrictStr] = None
    alpha_price_in_usd: Optional[StrictStr] = None
    amount: StrictStr
    block_number: int
    delegate: Key
    extrinsic_id: Optional[StrictStr] = None
    fee: Optional[StrictStr] = None
    id: StrictStr
    is_transfer: Optional[StrictBool] = None
    netuid: Optional[int] = None
    nominator: Key
    slippage: Optional[StrictStr] = None
    timestamp: datetime
    transfer_address: Optional[Key] = None
    usd: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["action", "alpha", "alpha_price_in_tao", "alpha_price_in_usd", "amount", "block_number", "delegate", "extrinsic_id", "fee", "id", "is_transfer", "netuid", "nominator", "slippage", "timestamp", "transfer_address", "usd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DelegationItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of delegate
        if self.delegate:
            _dict['delegate'] = self.delegate.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nominator
        if self.nominator:
            _dict['nominator'] = self.nominator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transfer_address
        if self.transfer_address:
            _dict['transfer_address'] = self.transfer_address.to_dict()
        # set to None if alpha (nullable) is None
        # and model_fields_set contains the field
        if self.alpha is None and "alpha" in self.model_fields_set:
            _dict['alpha'] = None

        # set to None if alpha_price_in_tao (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_price_in_tao is None and "alpha_price_in_tao" in self.model_fields_set:
            _dict['alpha_price_in_tao'] = None

        # set to None if alpha_price_in_usd (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_price_in_usd is None and "alpha_price_in_usd" in self.model_fields_set:
            _dict['alpha_price_in_usd'] = None

        # set to None if extrinsic_id (nullable) is None
        # and model_fields_set contains the field
        if self.extrinsic_id is None and "extrinsic_id" in self.model_fields_set:
            _dict['extrinsic_id'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if is_transfer (nullable) is None
        # and model_fields_set contains the field
        if self.is_transfer is None and "is_transfer" in self.model_fields_set:
            _dict['is_transfer'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if slippage (nullable) is None
        # and model_fields_set contains the field
        if self.slippage is None and "slippage" in self.model_fields_set:
            _dict['slippage'] = None

        # set to None if transfer_address (nullable) is None
        # and model_fields_set contains the field
        if self.transfer_address is None and "transfer_address" in self.model_fields_set:
            _dict['transfer_address'] = None

        # set to None if usd (nullable) is None
        # and model_fields_set contains the field
        if self.usd is None and "usd" in self.model_fields_set:
            _dict['usd'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DelegationItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "alpha": obj.get("alpha"),
            "alpha_price_in_tao": obj.get("alpha_price_in_tao"),
            "alpha_price_in_usd": obj.get("alpha_price_in_usd"),
            "amount": obj.get("amount"),
            "block_number": obj.get("block_number"),
            "delegate": Key.from_dict(obj.get("delegate")) if obj.get("delegate") is not None else None,
            "extrinsic_id": obj.get("extrinsic_id"),
            "fee": obj.get("fee"),
            "id": obj.get("id"),
            "is_transfer": obj.get("is_transfer"),
            "netuid": obj.get("netuid"),
            "nominator": Key.from_dict(obj.get("nominator")) if obj.get("nominator") is not None else None,
            "slippage": obj.get("slippage"),
            "timestamp": obj.get("timestamp"),
            "transfer_address": Key.from_dict(obj.get("transfer_address")) if obj.get("transfer_address") is not None else None,
            "usd": obj.get("usd")
        })
        return _obj


