# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DevActivityLatestItem(BaseModel):
    """
    DevActivityLatestItem
    """ # noqa: E501
    as_of_day: StrictStr
    comments_1d: int
    comments_30d: int
    comments_7d: int
    commits_1d: int
    commits_30d: int
    commits_7d: int
    days_since_last_event: int
    issues_closed_1d: int
    issues_closed_30d: int
    issues_closed_7d: int
    issues_opened_1d: int
    issues_opened_30d: int
    issues_opened_7d: int
    last_event_at: Optional[StrictStr] = None
    netuid: int
    prs_merged_1d: int
    prs_merged_30d: int
    prs_merged_7d: int
    prs_opened_1d: int
    prs_opened_30d: int
    prs_opened_7d: int
    repo_url: StrictStr
    reviews_1d: int
    reviews_30d: int
    reviews_7d: int
    unique_contributors_1d: int
    unique_contributors_30d: int
    unique_contributors_7d: int
    __properties: ClassVar[List[str]] = ["as_of_day", "comments_1d", "comments_30d", "comments_7d", "commits_1d", "commits_30d", "commits_7d", "days_since_last_event", "issues_closed_1d", "issues_closed_30d", "issues_closed_7d", "issues_opened_1d", "issues_opened_30d", "issues_opened_7d", "last_event_at", "netuid", "prs_merged_1d", "prs_merged_30d", "prs_merged_7d", "prs_opened_1d", "prs_opened_30d", "prs_opened_7d", "repo_url", "reviews_1d", "reviews_30d", "reviews_7d", "unique_contributors_1d", "unique_contributors_30d", "unique_contributors_7d"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DevActivityLatestItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if last_event_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_event_at is None and "last_event_at" in self.model_fields_set:
            _dict['last_event_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DevActivityLatestItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "as_of_day": obj.get("as_of_day"),
            "comments_1d": obj.get("comments_1d"),
            "comments_30d": obj.get("comments_30d"),
            "comments_7d": obj.get("comments_7d"),
            "commits_1d": obj.get("commits_1d"),
            "commits_30d": obj.get("commits_30d"),
            "commits_7d": obj.get("commits_7d"),
            "days_since_last_event": obj.get("days_since_last_event"),
            "issues_closed_1d": obj.get("issues_closed_1d"),
            "issues_closed_30d": obj.get("issues_closed_30d"),
            "issues_closed_7d": obj.get("issues_closed_7d"),
            "issues_opened_1d": obj.get("issues_opened_1d"),
            "issues_opened_30d": obj.get("issues_opened_30d"),
            "issues_opened_7d": obj.get("issues_opened_7d"),
            "last_event_at": obj.get("last_event_at"),
            "netuid": obj.get("netuid"),
            "prs_merged_1d": obj.get("prs_merged_1d"),
            "prs_merged_30d": obj.get("prs_merged_30d"),
            "prs_merged_7d": obj.get("prs_merged_7d"),
            "prs_opened_1d": obj.get("prs_opened_1d"),
            "prs_opened_30d": obj.get("prs_opened_30d"),
            "prs_opened_7d": obj.get("prs_opened_7d"),
            "repo_url": obj.get("repo_url"),
            "reviews_1d": obj.get("reviews_1d"),
            "reviews_30d": obj.get("reviews_30d"),
            "reviews_7d": obj.get("reviews_7d"),
            "unique_contributors_1d": obj.get("unique_contributors_1d"),
            "unique_contributors_30d": obj.get("unique_contributors_30d"),
            "unique_contributors_7d": obj.get("unique_contributors_7d")
        })
        return _obj


