# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DevActivityLatestOrder(str, Enum):
    """
    DevActivityLatestOrder
    """

    """
    allowed enum values
    """
    COMMITS1D_ASC = 'commits1d_asc'
    COMMITS1D_DESC = 'commits1d_desc'
    COMMITS7D_DESC = 'commits7d_desc'
    COMMITS7D_ASC = 'commits7d_asc'
    COMMITS30D_ASC = 'commits30d_asc'
    COMMITS30D_DESC = 'commits30d_desc'
    PRS_OPENED1D_ASC = 'prs_opened1d_asc'
    PRS_OPENED1D_DESC = 'prs_opened1d_desc'
    PRS_OPENED7D_ASC = 'prs_opened7d_asc'
    PRS_OPENED7D_DESC = 'prs_opened7d_desc'
    PRS_OPENED30D_ASC = 'prs_opened30d_asc'
    PRS_OPENED30D_DESC = 'prs_opened30d_desc'
    PRS_MERGED1D_ASC = 'prs_merged1d_asc'
    PRS_MERGED1D_DESC = 'prs_merged1d_desc'
    PRS_MERGED7D_ASC = 'prs_merged7d_asc'
    PRS_MERGED7D_DESC = 'prs_merged7d_desc'
    PRS_MERGED30D_ASC = 'prs_merged30d_asc'
    PRS_MERGED30D_DESC = 'prs_merged30d_desc'
    ISSUES_OPENED1D_ASC = 'issues_opened1d_asc'
    ISSUES_OPENED1D_DESC = 'issues_opened1d_desc'
    ISSUES_OPENED7D_ASC = 'issues_opened7d_asc'
    ISSUES_OPENED7D_DESC = 'issues_opened7d_desc'
    ISSUES_OPENED30D_ASC = 'issues_opened30d_asc'
    ISSUES_OPENED30D_DESC = 'issues_opened30d_desc'
    ISSUES_CLOSED1D_ASC = 'issues_closed1d_asc'
    ISSUES_CLOSED1D_DESC = 'issues_closed1d_desc'
    ISSUES_CLOSED7D_ASC = 'issues_closed7d_asc'
    ISSUES_CLOSED7D_DESC = 'issues_closed7d_desc'
    ISSUES_CLOSED30D_ASC = 'issues_closed30d_asc'
    ISSUES_CLOSED30D_DESC = 'issues_closed30d_desc'
    REVIEWS1D_ASC = 'reviews1d_asc'
    REVIEWS1D_DESC = 'reviews1d_desc'
    REVIEWS7D_ASC = 'reviews7d_asc'
    REVIEWS7D_DESC = 'reviews7d_desc'
    REVIEWS30D_ASC = 'reviews30d_asc'
    REVIEWS30D_DESC = 'reviews30d_desc'
    COMMENTS1D_ASC = 'comments1d_asc'
    COMMENTS1D_DESC = 'comments1d_desc'
    COMMENTS7D_ASC = 'comments7d_asc'
    COMMENTS7D_DESC = 'comments7d_desc'
    COMMENTS30D_ASC = 'comments30d_asc'
    COMMENTS30D_DESC = 'comments30d_desc'
    UNIQUE_CONTRIBUTORS1D_ASC = 'unique_contributors1d_asc'
    UNIQUE_CONTRIBUTORS1D_DESC = 'unique_contributors1d_desc'
    UNIQUE_CONTRIBUTORS7D_ASC = 'unique_contributors7d_asc'
    UNIQUE_CONTRIBUTORS7D_DESC = 'unique_contributors7d_desc'
    UNIQUE_CONTRIBUTORS30D_ASC = 'unique_contributors30d_asc'
    UNIQUE_CONTRIBUTORS30D_DESC = 'unique_contributors30d_desc'
    LAST_EVENT_AT_ASC = 'last_event_at_asc'
    LAST_EVENT_AT_DESC = 'last_event_at_desc'
    DAYS_SINCE_LAST_EVENT_ASC = 'days_since_last_event_asc'
    DAYS_SINCE_LAST_EVENT_DESC = 'days_since_last_event_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DevActivityLatestOrder from a JSON string"""
        return cls(json.loads(json_str))


