# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoLiquidityPositionOrder(str, Enum):
    """
    DtaoLiquidityPositionOrder
    """

    """
    allowed enum values
    """
    OPENED_ASC = 'opened_asc'
    OPENED_DESC = 'opened_desc'
    CLOSED_ASC = 'closed_asc'
    CLOSED_DESC = 'closed_desc'
    TAO_ASC = 'tao_asc'
    TAO_DESC = 'tao_desc'
    ALPHA_ASC = 'alpha_asc'
    ALPHA_DESC = 'alpha_desc'
    LIQUIDITY_ASC = 'liquidity_asc'
    LIQUIDITY_DESC = 'liquidity_desc'
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    FEES_CLAIMABLE_TAO_ASC = 'fees_claimable_tao_asc'
    FEES_CLAIMABLE_TAO_DESC = 'fees_claimable_tao_desc'
    FEES_CLAIMABLE_ALPHA_ASC = 'fees_claimable_alpha_asc'
    FEES_CLAIMABLE_ALPHA_DESC = 'fees_claimable_alpha_desc'
    FEES_CLAIMED_TAO_ASC = 'fees_claimed_tao_asc'
    FEES_CLAIMED_TAO_DESC = 'fees_claimed_tao_desc'
    FEES_CLAIMED_ALPHA_ASC = 'fees_claimed_alpha_asc'
    FEES_CLAIMED_ALPHA_DESC = 'fees_claimed_alpha_desc'
    TAO_COMMITTED_ASC = 'tao_committed_asc'
    TAO_COMMITTED_DESC = 'tao_committed_desc'
    ALPHA_COMMITTED_ASC = 'alpha_committed_asc'
    ALPHA_COMMITTED_DESC = 'alpha_committed_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoLiquidityPositionOrder from a JSON string"""
        return cls(json.loads(json_str))


