# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoStakeBalanceLatestItem(BaseModel):
    """
    DtaoStakeBalanceLatestItem
    """ # noqa: E501
    balance: StrictStr
    balance_as_tao: StrictStr
    block_number: int
    coldkey: Key
    hotkey: Key
    hotkey_name: Optional[StrictStr] = None
    netuid: int
    subnet_rank: int
    subnet_total_holders: int
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["balance", "balance_as_tao", "block_number", "coldkey", "hotkey", "hotkey_name", "netuid", "subnet_rank", "subnet_total_holders", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoStakeBalanceLatestItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if hotkey_name (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey_name is None and "hotkey_name" in self.model_fields_set:
            _dict['hotkey_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoStakeBalanceLatestItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "balance": obj.get("balance"),
            "balance_as_tao": obj.get("balance_as_tao"),
            "block_number": obj.get("block_number"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "hotkey_name": obj.get("hotkey_name"),
            "netuid": obj.get("netuid"),
            "subnet_rank": obj.get("subnet_rank"),
            "subnet_total_holders": obj.get("subnet_total_holders"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


