# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoSubnetEmissionOrder(str, Enum):
    """
    DtaoSubnetEmissionOrder
    """

    """
    allowed enum values
    """
    BLOCK_NUMBER_ASC = 'block_number_asc'
    BLOCK_NUMBER_DESC = 'block_number_desc'
    TIMESTAMP_ASC = 'timestamp_asc'
    TIMESTAMP_DESC = 'timestamp_desc'
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    TAO_IN_POOL_ASC = 'tao_in_pool_asc'
    TAO_IN_POOL_DESC = 'tao_in_pool_desc'
    ALPHA_IN_POOL_ASC = 'alpha_in_pool_asc'
    ALPHA_IN_POOL_DESC = 'alpha_in_pool_desc'
    ALPHA_REWARDS_ASC = 'alpha_rewards_asc'
    ALPHA_REWARDS_DESC = 'alpha_rewards_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoSubnetEmissionOrder from a JSON string"""
        return cls(json.loads(json_str))


