# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoPoolOrder(str, Enum):
    """
    DtaoPoolOrder
    """

    """
    allowed enum values
    """
    RANK_ASC = 'rank_asc'
    RANK_DESC = 'rank_desc'
    ROOT_PROP_ASC = 'root_prop_asc'
    ROOT_PROP_DESC = 'root_prop_desc'
    LIQUIDITY_ASC = 'liquidity_asc'
    LIQUIDITY_DESC = 'liquidity_desc'
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    PRICE_ASC = 'price_asc'
    PRICE_DESC = 'price_desc'
    FEAR_AND_GREED_INDEX_ASC = 'fear_and_greed_index_asc'
    FEAR_AND_GREED_INDEX_DESC = 'fear_and_greed_index_desc'
    MARKET_CAP_ASC = 'market_cap_asc'
    MARKET_CAP_DESC = 'market_cap_desc'
    MARKET_CAP_CHANGE_ONE_DAY_ASC = 'market_cap_change_one_day_asc'
    MARKET_CAP_CHANGE_ONE_DAY_DESC = 'market_cap_change_one_day_desc'
    TOTAL_TAO_ASC = 'total_tao_asc'
    TOTAL_TAO_DESC = 'total_tao_desc'
    TOTAL_ALPHA_ASC = 'total_alpha_asc'
    TOTAL_ALPHA_DESC = 'total_alpha_desc'
    ALPHA_IN_POOL_ASC = 'alpha_in_pool_asc'
    ALPHA_IN_POOL_DESC = 'alpha_in_pool_desc'
    ALPHA_STAKED_ASC = 'alpha_staked_asc'
    ALPHA_STAKED_DESC = 'alpha_staked_desc'
    TAO_VOLUME_ONE_DAY_ASC = 'tao_volume_one_day_asc'
    TAO_VOLUME_ONE_DAY_DESC = 'tao_volume_one_day_desc'
    PRICE_CHANGE_ONE_HOUR_ASC = 'price_change_one_hour_asc'
    PRICE_CHANGE_ONE_HOUR_DESC = 'price_change_one_hour_desc'
    PRICE_CHANGE_ONE_DAY_ASC = 'price_change_one_day_asc'
    PRICE_CHANGE_ONE_DAY_DESC = 'price_change_one_day_desc'
    PRICE_CHANGE_ONE_WEEK_ASC = 'price_change_one_week_asc'
    PRICE_CHANGE_ONE_WEEK_DESC = 'price_change_one_week_desc'
    PRICE_CHANGE_ONE_MONTH_ASC = 'price_change_one_month_asc'
    PRICE_CHANGE_ONE_MONTH_DESC = 'price_change_one_month_desc'
    ENABLED_USER_LIQUIDITY_ASC = 'enabled_user_liquidity_asc'
    ENABLED_USER_LIQUIDITY_DESC = 'enabled_user_liquidity_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoPoolOrder from a JSON string"""
        return cls(json.loads(json_str))


