# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.dtao_pool_daily_price_item import DtaoPoolDailyPriceItem
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoPoolItem(BaseModel):
    """
    DtaoPoolItem
    """ # noqa: E501
    alpha_buy_volume_24_hr: StrictStr
    alpha_in_pool: StrictStr
    alpha_sell_volume_24_hr: StrictStr
    alpha_sqrt_price: Optional[StrictStr] = None
    alpha_staked: StrictStr
    alpha_volume_24_hr: StrictStr
    alpha_volume_24_hr_change_1_day: Optional[StrictStr] = None
    block_number: int
    buyers_24_hr: int
    buys_24_hr: int
    current_tick: Optional[int] = None
    enabled_user_liquidity: Optional[StrictBool] = None
    fear_and_greed_index: Optional[StrictStr] = None
    fear_and_greed_sentiment: Optional[StrictStr] = None
    fee_global_alpha: Optional[StrictStr] = None
    fee_global_tao: Optional[StrictStr] = None
    fee_rate: Optional[StrictStr] = None
    highest_price_24_hr: Optional[StrictStr] = None
    last_price: Optional[StrictStr] = None
    liquidity: StrictStr
    liquidity_raw: Optional[StrictStr] = None
    lowest_price_24_hr: Optional[StrictStr] = None
    market_cap: StrictStr
    market_cap_change_1_day: Optional[StrictStr] = None
    name: StrictStr
    netuid: int
    price: StrictStr
    price_change_1_day: Optional[StrictStr] = None
    price_change_1_hour: Optional[StrictStr] = None
    price_change_1_month: Optional[StrictStr] = None
    price_change_1_week: Optional[StrictStr] = None
    protocol_provided_alpha: Optional[StrictStr] = None
    protocol_provided_tao: Optional[StrictStr] = None
    rank: int
    root_prop: StrictStr
    sellers_24_hr: int
    sells_24_hr: int
    seven_day_prices: List[DtaoPoolDailyPriceItem]
    startup_mode: StrictBool
    swap_v3_initialized: Optional[StrictBool] = None
    symbol: StrictStr
    tao_buy_volume_24_hr: StrictStr
    tao_sell_volume_24_hr: StrictStr
    tao_volume_24_hr: StrictStr
    tao_volume_24_hr_change_1_day: Optional[StrictStr] = None
    timestamp: datetime
    total_alpha: StrictStr
    total_tao: StrictStr
    user_provided_alpha: Optional[StrictStr] = None
    user_provided_tao: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["alpha_buy_volume_24_hr", "alpha_in_pool", "alpha_sell_volume_24_hr", "alpha_sqrt_price", "alpha_staked", "alpha_volume_24_hr", "alpha_volume_24_hr_change_1_day", "block_number", "buyers_24_hr", "buys_24_hr", "current_tick", "enabled_user_liquidity", "fear_and_greed_index", "fear_and_greed_sentiment", "fee_global_alpha", "fee_global_tao", "fee_rate", "highest_price_24_hr", "last_price", "liquidity", "liquidity_raw", "lowest_price_24_hr", "market_cap", "market_cap_change_1_day", "name", "netuid", "price", "price_change_1_day", "price_change_1_hour", "price_change_1_month", "price_change_1_week", "protocol_provided_alpha", "protocol_provided_tao", "rank", "root_prop", "sellers_24_hr", "sells_24_hr", "seven_day_prices", "startup_mode", "swap_v3_initialized", "symbol", "tao_buy_volume_24_hr", "tao_sell_volume_24_hr", "tao_volume_24_hr", "tao_volume_24_hr_change_1_day", "timestamp", "total_alpha", "total_tao", "user_provided_alpha", "user_provided_tao"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoPoolItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in seven_day_prices (list)
        _items = []
        if self.seven_day_prices:
            for _item in self.seven_day_prices:
                if _item:
                    _items.append(_item.to_dict())
            _dict['seven_day_prices'] = _items
        # set to None if alpha_sqrt_price (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_sqrt_price is None and "alpha_sqrt_price" in self.model_fields_set:
            _dict['alpha_sqrt_price'] = None

        # set to None if alpha_volume_24_hr_change_1_day (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_volume_24_hr_change_1_day is None and "alpha_volume_24_hr_change_1_day" in self.model_fields_set:
            _dict['alpha_volume_24_hr_change_1_day'] = None

        # set to None if current_tick (nullable) is None
        # and model_fields_set contains the field
        if self.current_tick is None and "current_tick" in self.model_fields_set:
            _dict['current_tick'] = None

        # set to None if enabled_user_liquidity (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_user_liquidity is None and "enabled_user_liquidity" in self.model_fields_set:
            _dict['enabled_user_liquidity'] = None

        # set to None if fear_and_greed_index (nullable) is None
        # and model_fields_set contains the field
        if self.fear_and_greed_index is None and "fear_and_greed_index" in self.model_fields_set:
            _dict['fear_and_greed_index'] = None

        # set to None if fear_and_greed_sentiment (nullable) is None
        # and model_fields_set contains the field
        if self.fear_and_greed_sentiment is None and "fear_and_greed_sentiment" in self.model_fields_set:
            _dict['fear_and_greed_sentiment'] = None

        # set to None if fee_global_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.fee_global_alpha is None and "fee_global_alpha" in self.model_fields_set:
            _dict['fee_global_alpha'] = None

        # set to None if fee_global_tao (nullable) is None
        # and model_fields_set contains the field
        if self.fee_global_tao is None and "fee_global_tao" in self.model_fields_set:
            _dict['fee_global_tao'] = None

        # set to None if fee_rate (nullable) is None
        # and model_fields_set contains the field
        if self.fee_rate is None and "fee_rate" in self.model_fields_set:
            _dict['fee_rate'] = None

        # set to None if highest_price_24_hr (nullable) is None
        # and model_fields_set contains the field
        if self.highest_price_24_hr is None and "highest_price_24_hr" in self.model_fields_set:
            _dict['highest_price_24_hr'] = None

        # set to None if last_price (nullable) is None
        # and model_fields_set contains the field
        if self.last_price is None and "last_price" in self.model_fields_set:
            _dict['last_price'] = None

        # set to None if liquidity_raw (nullable) is None
        # and model_fields_set contains the field
        if self.liquidity_raw is None and "liquidity_raw" in self.model_fields_set:
            _dict['liquidity_raw'] = None

        # set to None if lowest_price_24_hr (nullable) is None
        # and model_fields_set contains the field
        if self.lowest_price_24_hr is None and "lowest_price_24_hr" in self.model_fields_set:
            _dict['lowest_price_24_hr'] = None

        # set to None if market_cap_change_1_day (nullable) is None
        # and model_fields_set contains the field
        if self.market_cap_change_1_day is None and "market_cap_change_1_day" in self.model_fields_set:
            _dict['market_cap_change_1_day'] = None

        # set to None if price_change_1_day (nullable) is None
        # and model_fields_set contains the field
        if self.price_change_1_day is None and "price_change_1_day" in self.model_fields_set:
            _dict['price_change_1_day'] = None

        # set to None if price_change_1_hour (nullable) is None
        # and model_fields_set contains the field
        if self.price_change_1_hour is None and "price_change_1_hour" in self.model_fields_set:
            _dict['price_change_1_hour'] = None

        # set to None if price_change_1_month (nullable) is None
        # and model_fields_set contains the field
        if self.price_change_1_month is None and "price_change_1_month" in self.model_fields_set:
            _dict['price_change_1_month'] = None

        # set to None if price_change_1_week (nullable) is None
        # and model_fields_set contains the field
        if self.price_change_1_week is None and "price_change_1_week" in self.model_fields_set:
            _dict['price_change_1_week'] = None

        # set to None if protocol_provided_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_provided_alpha is None and "protocol_provided_alpha" in self.model_fields_set:
            _dict['protocol_provided_alpha'] = None

        # set to None if protocol_provided_tao (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_provided_tao is None and "protocol_provided_tao" in self.model_fields_set:
            _dict['protocol_provided_tao'] = None

        # set to None if swap_v3_initialized (nullable) is None
        # and model_fields_set contains the field
        if self.swap_v3_initialized is None and "swap_v3_initialized" in self.model_fields_set:
            _dict['swap_v3_initialized'] = None

        # set to None if tao_volume_24_hr_change_1_day (nullable) is None
        # and model_fields_set contains the field
        if self.tao_volume_24_hr_change_1_day is None and "tao_volume_24_hr_change_1_day" in self.model_fields_set:
            _dict['tao_volume_24_hr_change_1_day'] = None

        # set to None if user_provided_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.user_provided_alpha is None and "user_provided_alpha" in self.model_fields_set:
            _dict['user_provided_alpha'] = None

        # set to None if user_provided_tao (nullable) is None
        # and model_fields_set contains the field
        if self.user_provided_tao is None and "user_provided_tao" in self.model_fields_set:
            _dict['user_provided_tao'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoPoolItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_buy_volume_24_hr": obj.get("alpha_buy_volume_24_hr"),
            "alpha_in_pool": obj.get("alpha_in_pool"),
            "alpha_sell_volume_24_hr": obj.get("alpha_sell_volume_24_hr"),
            "alpha_sqrt_price": obj.get("alpha_sqrt_price"),
            "alpha_staked": obj.get("alpha_staked"),
            "alpha_volume_24_hr": obj.get("alpha_volume_24_hr"),
            "alpha_volume_24_hr_change_1_day": obj.get("alpha_volume_24_hr_change_1_day"),
            "block_number": obj.get("block_number"),
            "buyers_24_hr": obj.get("buyers_24_hr"),
            "buys_24_hr": obj.get("buys_24_hr"),
            "current_tick": obj.get("current_tick"),
            "enabled_user_liquidity": obj.get("enabled_user_liquidity"),
            "fear_and_greed_index": obj.get("fear_and_greed_index"),
            "fear_and_greed_sentiment": obj.get("fear_and_greed_sentiment"),
            "fee_global_alpha": obj.get("fee_global_alpha"),
            "fee_global_tao": obj.get("fee_global_tao"),
            "fee_rate": obj.get("fee_rate"),
            "highest_price_24_hr": obj.get("highest_price_24_hr"),
            "last_price": obj.get("last_price"),
            "liquidity": obj.get("liquidity"),
            "liquidity_raw": obj.get("liquidity_raw"),
            "lowest_price_24_hr": obj.get("lowest_price_24_hr"),
            "market_cap": obj.get("market_cap"),
            "market_cap_change_1_day": obj.get("market_cap_change_1_day"),
            "name": obj.get("name"),
            "netuid": obj.get("netuid"),
            "price": obj.get("price"),
            "price_change_1_day": obj.get("price_change_1_day"),
            "price_change_1_hour": obj.get("price_change_1_hour"),
            "price_change_1_month": obj.get("price_change_1_month"),
            "price_change_1_week": obj.get("price_change_1_week"),
            "protocol_provided_alpha": obj.get("protocol_provided_alpha"),
            "protocol_provided_tao": obj.get("protocol_provided_tao"),
            "rank": obj.get("rank"),
            "root_prop": obj.get("root_prop"),
            "sellers_24_hr": obj.get("sellers_24_hr"),
            "sells_24_hr": obj.get("sells_24_hr"),
            "seven_day_prices": [DtaoPoolDailyPriceItem.from_dict(_item) for _item in obj.get("seven_day_prices")] if obj.get("seven_day_prices") is not None else None,
            "startup_mode": obj.get("startup_mode"),
            "swap_v3_initialized": obj.get("swap_v3_initialized"),
            "symbol": obj.get("symbol"),
            "tao_buy_volume_24_hr": obj.get("tao_buy_volume_24_hr"),
            "tao_sell_volume_24_hr": obj.get("tao_sell_volume_24_hr"),
            "tao_volume_24_hr": obj.get("tao_volume_24_hr"),
            "tao_volume_24_hr_change_1_day": obj.get("tao_volume_24_hr_change_1_day"),
            "timestamp": obj.get("timestamp"),
            "total_alpha": obj.get("total_alpha"),
            "total_tao": obj.get("total_tao"),
            "user_provided_alpha": obj.get("user_provided_alpha"),
            "user_provided_tao": obj.get("user_provided_tao")
        })
        return _obj


