# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoStakeBalanceLatestOrder(str, Enum):
    """
    DtaoStakeBalanceLatestOrder
    """

    """
    allowed enum values
    """
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    SUBNET_RANK_ASC = 'subnet_rank_asc'
    SUBNET_RANK_DESC = 'subnet_rank_desc'
    BALANCE_ASC = 'balance_asc'
    BALANCE_DESC = 'balance_desc'
    BALANCE_AS_TAO_ASC = 'balance_as_tao_asc'
    BALANCE_AS_TAO_DESC = 'balance_as_tao_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoStakeBalanceLatestOrder from a JSON string"""
        return cls(json.loads(json_str))


