# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoValidatorDividendsItem(BaseModel):
    """
    DtaoValidatorDividendsItem
    """ # noqa: E501
    block_number: int
    day: date
    epochs: int
    hotkey: Key
    name: Optional[StrictStr] = None
    netuid: int
    nominator_alpha_dividends: StrictStr
    nominator_return_per_kt_alpha: StrictStr
    nominator_return_per_kt_root: StrictStr
    nominator_root_dividends: StrictStr
    take: StrictStr
    tempo: int
    timestamp: datetime
    total_hotkey_alpha: StrictStr
    total_hotkey_root: StrictStr
    validator_alpha_dividends: StrictStr
    validator_root_dividends: StrictStr
    __properties: ClassVar[List[str]] = ["block_number", "day", "epochs", "hotkey", "name", "netuid", "nominator_alpha_dividends", "nominator_return_per_kt_alpha", "nominator_return_per_kt_root", "nominator_root_dividends", "take", "tempo", "timestamp", "total_hotkey_alpha", "total_hotkey_root", "validator_alpha_dividends", "validator_root_dividends"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorDividendsItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoValidatorDividendsItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "day": obj.get("day"),
            "epochs": obj.get("epochs"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "name": obj.get("name"),
            "netuid": obj.get("netuid"),
            "nominator_alpha_dividends": obj.get("nominator_alpha_dividends"),
            "nominator_return_per_kt_alpha": obj.get("nominator_return_per_kt_alpha"),
            "nominator_return_per_kt_root": obj.get("nominator_return_per_kt_root"),
            "nominator_root_dividends": obj.get("nominator_root_dividends"),
            "take": obj.get("take"),
            "tempo": obj.get("tempo"),
            "timestamp": obj.get("timestamp"),
            "total_hotkey_alpha": obj.get("total_hotkey_alpha"),
            "total_hotkey_root": obj.get("total_hotkey_root"),
            "validator_alpha_dividends": obj.get("validator_alpha_dividends"),
            "validator_root_dividends": obj.get("validator_root_dividends")
        })
        return _obj


