# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoPoolHistoryItem(BaseModel):
    """
    DtaoPoolHistoryItem
    """ # noqa: E501
    alpha_in_pool: StrictStr
    alpha_sqrt_price: Optional[StrictStr] = None
    alpha_staked: StrictStr
    block_number: int
    current_tick: Optional[int] = None
    enabled_user_liquidity: Optional[StrictBool] = None
    fee_global_alpha: Optional[StrictStr] = None
    fee_global_tao: Optional[StrictStr] = None
    fee_rate: Optional[StrictStr] = None
    liquidity: StrictStr
    liquidity_raw: Optional[StrictStr] = None
    market_cap: StrictStr
    name: StrictStr
    netuid: int
    price: StrictStr
    protocol_provided_alpha: Optional[StrictStr] = None
    protocol_provided_tao: Optional[StrictStr] = None
    rank: int
    root_prop: StrictStr
    startup_mode: StrictBool
    swap_v3_initialized: Optional[StrictBool] = None
    symbol: StrictStr
    timestamp: datetime
    total_alpha: StrictStr
    total_tao: StrictStr
    user_provided_alpha: Optional[StrictStr] = None
    user_provided_tao: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["alpha_in_pool", "alpha_sqrt_price", "alpha_staked", "block_number", "current_tick", "enabled_user_liquidity", "fee_global_alpha", "fee_global_tao", "fee_rate", "liquidity", "liquidity_raw", "market_cap", "name", "netuid", "price", "protocol_provided_alpha", "protocol_provided_tao", "rank", "root_prop", "startup_mode", "swap_v3_initialized", "symbol", "timestamp", "total_alpha", "total_tao", "user_provided_alpha", "user_provided_tao"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoPoolHistoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if alpha_sqrt_price (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_sqrt_price is None and "alpha_sqrt_price" in self.model_fields_set:
            _dict['alpha_sqrt_price'] = None

        # set to None if current_tick (nullable) is None
        # and model_fields_set contains the field
        if self.current_tick is None and "current_tick" in self.model_fields_set:
            _dict['current_tick'] = None

        # set to None if enabled_user_liquidity (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_user_liquidity is None and "enabled_user_liquidity" in self.model_fields_set:
            _dict['enabled_user_liquidity'] = None

        # set to None if fee_global_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.fee_global_alpha is None and "fee_global_alpha" in self.model_fields_set:
            _dict['fee_global_alpha'] = None

        # set to None if fee_global_tao (nullable) is None
        # and model_fields_set contains the field
        if self.fee_global_tao is None and "fee_global_tao" in self.model_fields_set:
            _dict['fee_global_tao'] = None

        # set to None if fee_rate (nullable) is None
        # and model_fields_set contains the field
        if self.fee_rate is None and "fee_rate" in self.model_fields_set:
            _dict['fee_rate'] = None

        # set to None if liquidity_raw (nullable) is None
        # and model_fields_set contains the field
        if self.liquidity_raw is None and "liquidity_raw" in self.model_fields_set:
            _dict['liquidity_raw'] = None

        # set to None if protocol_provided_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_provided_alpha is None and "protocol_provided_alpha" in self.model_fields_set:
            _dict['protocol_provided_alpha'] = None

        # set to None if protocol_provided_tao (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_provided_tao is None and "protocol_provided_tao" in self.model_fields_set:
            _dict['protocol_provided_tao'] = None

        # set to None if swap_v3_initialized (nullable) is None
        # and model_fields_set contains the field
        if self.swap_v3_initialized is None and "swap_v3_initialized" in self.model_fields_set:
            _dict['swap_v3_initialized'] = None

        # set to None if user_provided_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.user_provided_alpha is None and "user_provided_alpha" in self.model_fields_set:
            _dict['user_provided_alpha'] = None

        # set to None if user_provided_tao (nullable) is None
        # and model_fields_set contains the field
        if self.user_provided_tao is None and "user_provided_tao" in self.model_fields_set:
            _dict['user_provided_tao'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoPoolHistoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_in_pool": obj.get("alpha_in_pool"),
            "alpha_sqrt_price": obj.get("alpha_sqrt_price"),
            "alpha_staked": obj.get("alpha_staked"),
            "block_number": obj.get("block_number"),
            "current_tick": obj.get("current_tick"),
            "enabled_user_liquidity": obj.get("enabled_user_liquidity"),
            "fee_global_alpha": obj.get("fee_global_alpha"),
            "fee_global_tao": obj.get("fee_global_tao"),
            "fee_rate": obj.get("fee_rate"),
            "liquidity": obj.get("liquidity"),
            "liquidity_raw": obj.get("liquidity_raw"),
            "market_cap": obj.get("market_cap"),
            "name": obj.get("name"),
            "netuid": obj.get("netuid"),
            "price": obj.get("price"),
            "protocol_provided_alpha": obj.get("protocol_provided_alpha"),
            "protocol_provided_tao": obj.get("protocol_provided_tao"),
            "rank": obj.get("rank"),
            "root_prop": obj.get("root_prop"),
            "startup_mode": obj.get("startup_mode"),
            "swap_v3_initialized": obj.get("swap_v3_initialized"),
            "symbol": obj.get("symbol"),
            "timestamp": obj.get("timestamp"),
            "total_alpha": obj.get("total_alpha"),
            "total_tao": obj.get("total_tao"),
            "user_provided_alpha": obj.get("user_provided_alpha"),
            "user_provided_tao": obj.get("user_provided_tao")
        })
        return _obj


