# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoValidatorYieldLatestOrder(str, Enum):
    """
    DtaoValidatorYieldLatestOrder
    """

    """
    allowed enum values
    """
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    NAME_ASC = 'name_asc'
    NAME_DESC = 'name_desc'
    STAKE_ASC = 'stake_asc'
    STAKE_DESC = 'stake_desc'
    ONE_HOUR_APY_ASC = 'one_hour_apy_asc'
    ONE_HOUR_APY_DESC = 'one_hour_apy_desc'
    ONE_DAY_APY_ASC = 'one_day_apy_asc'
    ONE_DAY_APY_DESC = 'one_day_apy_desc'
    SEVEN_DAY_APY_ASC = 'seven_day_apy_asc'
    SEVEN_DAY_APY_DESC = 'seven_day_apy_desc'
    THIRTY_DAY_APY_ASC = 'thirty_day_apy_asc'
    THIRTY_DAY_APY_DESC = 'thirty_day_apy_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorYieldLatestOrder from a JSON string"""
        return cls(json.loads(json_str))


