# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoLiquidityDistributionRequest(BaseModel):
    """
    DtaoLiquidityDistributionRequest
    """ # noqa: E501
    log_scale: Optional[StrictBool] = Field(default=None, description="Use logarithmic scale for price distribution (default: true)")
    max_price: Optional[StrictStr] = None
    min_price: Optional[StrictStr] = None
    netuid: int
    num_points: Optional[int] = Field(default=None, description="Number of data points to return (default: 200, max: 1000)")
    __properties: ClassVar[List[str]] = ["log_scale", "max_price", "min_price", "netuid", "num_points"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoLiquidityDistributionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if log_scale (nullable) is None
        # and model_fields_set contains the field
        if self.log_scale is None and "log_scale" in self.model_fields_set:
            _dict['log_scale'] = None

        # set to None if max_price (nullable) is None
        # and model_fields_set contains the field
        if self.max_price is None and "max_price" in self.model_fields_set:
            _dict['max_price'] = None

        # set to None if min_price (nullable) is None
        # and model_fields_set contains the field
        if self.min_price is None and "min_price" in self.model_fields_set:
            _dict['min_price'] = None

        # set to None if num_points (nullable) is None
        # and model_fields_set contains the field
        if self.num_points is None and "num_points" in self.model_fields_set:
            _dict['num_points'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoLiquidityDistributionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "log_scale": obj.get("log_scale"),
            "max_price": obj.get("max_price"),
            "min_price": obj.get("min_price"),
            "netuid": obj.get("netuid"),
            "num_points": obj.get("num_points")
        })
        return _obj


