# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoValidatorItem(BaseModel):
    """
    DtaoValidatorItem
    """ # noqa: E501
    active_subnets: int
    alpha_rank: int
    block_number: int
    coldkey: Key
    created_on_date: date
    dominance: StrictStr
    dominance_24_hr_change: StrictStr
    global_alpha_stake_as_tao: StrictStr
    global_nominators: int
    global_nominators_24_hr_change: int
    global_weighted_stake: StrictStr
    global_weighted_stake_24_hr_change: StrictStr
    hotkey: Key
    name: Optional[StrictStr] = None
    nominator_return_per_day: StrictStr
    rank: int
    root_rank: int
    root_stake: StrictStr
    take: StrictStr
    timestamp: datetime
    validator_return_per_day: StrictStr
    weighted_root_stake: StrictStr
    __properties: ClassVar[List[str]] = ["active_subnets", "alpha_rank", "block_number", "coldkey", "created_on_date", "dominance", "dominance_24_hr_change", "global_alpha_stake_as_tao", "global_nominators", "global_nominators_24_hr_change", "global_weighted_stake", "global_weighted_stake_24_hr_change", "hotkey", "name", "nominator_return_per_day", "rank", "root_rank", "root_stake", "take", "timestamp", "validator_return_per_day", "weighted_root_stake"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoValidatorItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_subnets": obj.get("active_subnets"),
            "alpha_rank": obj.get("alpha_rank"),
            "block_number": obj.get("block_number"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "created_on_date": obj.get("created_on_date"),
            "dominance": obj.get("dominance"),
            "dominance_24_hr_change": obj.get("dominance_24_hr_change"),
            "global_alpha_stake_as_tao": obj.get("global_alpha_stake_as_tao"),
            "global_nominators": obj.get("global_nominators"),
            "global_nominators_24_hr_change": obj.get("global_nominators_24_hr_change"),
            "global_weighted_stake": obj.get("global_weighted_stake"),
            "global_weighted_stake_24_hr_change": obj.get("global_weighted_stake_24_hr_change"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "name": obj.get("name"),
            "nominator_return_per_day": obj.get("nominator_return_per_day"),
            "rank": obj.get("rank"),
            "root_rank": obj.get("root_rank"),
            "root_stake": obj.get("root_stake"),
            "take": obj.get("take"),
            "timestamp": obj.get("timestamp"),
            "validator_return_per_day": obj.get("validator_return_per_day"),
            "weighted_root_stake": obj.get("weighted_root_stake")
        })
        return _obj


