# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoValidatorPerformanceItem(BaseModel):
    """
    DtaoValidatorPerformanceItem
    """ # noqa: E501
    alpha: StrictStr
    block_number: int
    childkey_take: StrictStr
    coldkey: Key
    dividends: StrictStr
    dominance: StrictStr
    family_alpha: StrictStr
    family_root_weight: StrictStr
    family_subnet_weight: StrictStr
    hotkey: Key
    last_updated: int
    mech_last_updated: List[int]
    name: Optional[StrictStr] = None
    netuid: int
    nominator_return_per_day: StrictStr
    nominators: int
    position: int
    proportion: StrictStr
    ratio: StrictStr
    root_weight: StrictStr
    subnet_weight: StrictStr
    take: StrictStr
    timestamp: datetime
    uid: int
    validator_return_per_day: StrictStr
    validator_type: StrictStr
    vtrust: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["alpha", "block_number", "childkey_take", "coldkey", "dividends", "dominance", "family_alpha", "family_root_weight", "family_subnet_weight", "hotkey", "last_updated", "mech_last_updated", "name", "netuid", "nominator_return_per_day", "nominators", "position", "proportion", "ratio", "root_weight", "subnet_weight", "take", "timestamp", "uid", "validator_return_per_day", "validator_type", "vtrust"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorPerformanceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if vtrust (nullable) is None
        # and model_fields_set contains the field
        if self.vtrust is None and "vtrust" in self.model_fields_set:
            _dict['vtrust'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoValidatorPerformanceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha": obj.get("alpha"),
            "block_number": obj.get("block_number"),
            "childkey_take": obj.get("childkey_take"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "dividends": obj.get("dividends"),
            "dominance": obj.get("dominance"),
            "family_alpha": obj.get("family_alpha"),
            "family_root_weight": obj.get("family_root_weight"),
            "family_subnet_weight": obj.get("family_subnet_weight"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "last_updated": obj.get("last_updated"),
            "mech_last_updated": obj.get("mech_last_updated"),
            "name": obj.get("name"),
            "netuid": obj.get("netuid"),
            "nominator_return_per_day": obj.get("nominator_return_per_day"),
            "nominators": obj.get("nominators"),
            "position": obj.get("position"),
            "proportion": obj.get("proportion"),
            "ratio": obj.get("ratio"),
            "root_weight": obj.get("root_weight"),
            "subnet_weight": obj.get("subnet_weight"),
            "take": obj.get("take"),
            "timestamp": obj.get("timestamp"),
            "uid": obj.get("uid"),
            "validator_return_per_day": obj.get("validator_return_per_day"),
            "validator_type": obj.get("validator_type"),
            "vtrust": obj.get("vtrust")
        })
        return _obj


