# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoLiquidityPositionEventItem(BaseModel):
    """
    DtaoLiquidityPositionEventItem
    """ # noqa: E501
    alpha_committed: StrictStr
    alpha_withdrawn: StrictStr
    block_number: int
    coldkey: Key
    fees_claimed_alpha: StrictStr
    fees_claimed_tao: StrictStr
    hotkey: Key
    id: StrictStr
    liquidity: StrictStr
    max_price: StrictStr
    min_price: StrictStr
    netuid: int
    position_id: StrictStr
    tao_committed: StrictStr
    tao_withdrawn: StrictStr
    tick_high: int
    tick_low: int
    timestamp: datetime
    type: StrictStr
    __properties: ClassVar[List[str]] = ["alpha_committed", "alpha_withdrawn", "block_number", "coldkey", "fees_claimed_alpha", "fees_claimed_tao", "hotkey", "id", "liquidity", "max_price", "min_price", "netuid", "position_id", "tao_committed", "tao_withdrawn", "tick_high", "tick_low", "timestamp", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoLiquidityPositionEventItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoLiquidityPositionEventItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_committed": obj.get("alpha_committed"),
            "alpha_withdrawn": obj.get("alpha_withdrawn"),
            "block_number": obj.get("block_number"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "fees_claimed_alpha": obj.get("fees_claimed_alpha"),
            "fees_claimed_tao": obj.get("fees_claimed_tao"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "id": obj.get("id"),
            "liquidity": obj.get("liquidity"),
            "max_price": obj.get("max_price"),
            "min_price": obj.get("min_price"),
            "netuid": obj.get("netuid"),
            "position_id": obj.get("position_id"),
            "tao_committed": obj.get("tao_committed"),
            "tao_withdrawn": obj.get("tao_withdrawn"),
            "tick_high": obj.get("tick_high"),
            "tick_low": obj.get("tick_low"),
            "timestamp": obj.get("timestamp"),
            "type": obj.get("type")
        })
        return _obj


