# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoStakeBalancePortfolioItem(BaseModel):
    """
    DtaoStakeBalancePortfolioItem
    """ # noqa: E501
    average_purchase_price_tao: StrictStr
    average_purchase_price_usd: StrictStr
    average_sale_price_tao: StrictStr
    average_sale_price_usd: StrictStr
    balance: StrictStr
    balance_as_tao: StrictStr
    coldkey: Key
    current_market_price_tao: StrictStr
    current_market_price_usd: StrictStr
    hotkey: Key
    hotkey_name: Optional[StrictStr] = None
    netuid: int
    period_start_alpha: Optional[StrictStr] = None
    period_start_alpha_cost_in_usd: Optional[StrictStr] = None
    period_start_alpha_price_in_tao: Optional[StrictStr] = None
    period_start_tao_price_in_usd: Optional[StrictStr] = None
    realised_profit_tao: StrictStr
    realised_profit_usd: StrictStr
    subnet_rank: Optional[int] = None
    subnet_total_holders: Optional[int] = None
    total_bought_alpha: StrictStr
    total_bought_alpha_as_tao: StrictStr
    total_bought_alpha_as_usd: StrictStr
    total_buys: int
    total_earned_alpha: StrictStr
    total_earned_alpha_as_tao: StrictStr
    total_earned_alpha_as_usd: StrictStr
    total_sells: int
    total_sold_alpha: StrictStr
    total_sold_alpha_as_tao: StrictStr
    total_sold_alpha_as_usd: StrictStr
    total_transferred_in_alpha: StrictStr
    total_transferred_in_alpha_as_tao: StrictStr
    total_transferred_in_alpha_as_usd: StrictStr
    total_transferred_out_alpha: StrictStr
    total_transferred_out_alpha_as_tao: StrictStr
    total_transferred_out_alpha_as_usd: StrictStr
    total_transfers_in: int
    total_transfers_out: int
    unrealised_profit_tao: StrictStr
    unrealised_profit_usd: StrictStr
    __properties: ClassVar[List[str]] = ["average_purchase_price_tao", "average_purchase_price_usd", "average_sale_price_tao", "average_sale_price_usd", "balance", "balance_as_tao", "coldkey", "current_market_price_tao", "current_market_price_usd", "hotkey", "hotkey_name", "netuid", "period_start_alpha", "period_start_alpha_cost_in_usd", "period_start_alpha_price_in_tao", "period_start_tao_price_in_usd", "realised_profit_tao", "realised_profit_usd", "subnet_rank", "subnet_total_holders", "total_bought_alpha", "total_bought_alpha_as_tao", "total_bought_alpha_as_usd", "total_buys", "total_earned_alpha", "total_earned_alpha_as_tao", "total_earned_alpha_as_usd", "total_sells", "total_sold_alpha", "total_sold_alpha_as_tao", "total_sold_alpha_as_usd", "total_transferred_in_alpha", "total_transferred_in_alpha_as_tao", "total_transferred_in_alpha_as_usd", "total_transferred_out_alpha", "total_transferred_out_alpha_as_tao", "total_transferred_out_alpha_as_usd", "total_transfers_in", "total_transfers_out", "unrealised_profit_tao", "unrealised_profit_usd"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoStakeBalancePortfolioItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if hotkey_name (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey_name is None and "hotkey_name" in self.model_fields_set:
            _dict['hotkey_name'] = None

        # set to None if period_start_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.period_start_alpha is None and "period_start_alpha" in self.model_fields_set:
            _dict['period_start_alpha'] = None

        # set to None if period_start_alpha_cost_in_usd (nullable) is None
        # and model_fields_set contains the field
        if self.period_start_alpha_cost_in_usd is None and "period_start_alpha_cost_in_usd" in self.model_fields_set:
            _dict['period_start_alpha_cost_in_usd'] = None

        # set to None if period_start_alpha_price_in_tao (nullable) is None
        # and model_fields_set contains the field
        if self.period_start_alpha_price_in_tao is None and "period_start_alpha_price_in_tao" in self.model_fields_set:
            _dict['period_start_alpha_price_in_tao'] = None

        # set to None if period_start_tao_price_in_usd (nullable) is None
        # and model_fields_set contains the field
        if self.period_start_tao_price_in_usd is None and "period_start_tao_price_in_usd" in self.model_fields_set:
            _dict['period_start_tao_price_in_usd'] = None

        # set to None if subnet_rank (nullable) is None
        # and model_fields_set contains the field
        if self.subnet_rank is None and "subnet_rank" in self.model_fields_set:
            _dict['subnet_rank'] = None

        # set to None if subnet_total_holders (nullable) is None
        # and model_fields_set contains the field
        if self.subnet_total_holders is None and "subnet_total_holders" in self.model_fields_set:
            _dict['subnet_total_holders'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoStakeBalancePortfolioItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "average_purchase_price_tao": obj.get("average_purchase_price_tao"),
            "average_purchase_price_usd": obj.get("average_purchase_price_usd"),
            "average_sale_price_tao": obj.get("average_sale_price_tao"),
            "average_sale_price_usd": obj.get("average_sale_price_usd"),
            "balance": obj.get("balance"),
            "balance_as_tao": obj.get("balance_as_tao"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "current_market_price_tao": obj.get("current_market_price_tao"),
            "current_market_price_usd": obj.get("current_market_price_usd"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "hotkey_name": obj.get("hotkey_name"),
            "netuid": obj.get("netuid"),
            "period_start_alpha": obj.get("period_start_alpha"),
            "period_start_alpha_cost_in_usd": obj.get("period_start_alpha_cost_in_usd"),
            "period_start_alpha_price_in_tao": obj.get("period_start_alpha_price_in_tao"),
            "period_start_tao_price_in_usd": obj.get("period_start_tao_price_in_usd"),
            "realised_profit_tao": obj.get("realised_profit_tao"),
            "realised_profit_usd": obj.get("realised_profit_usd"),
            "subnet_rank": obj.get("subnet_rank"),
            "subnet_total_holders": obj.get("subnet_total_holders"),
            "total_bought_alpha": obj.get("total_bought_alpha"),
            "total_bought_alpha_as_tao": obj.get("total_bought_alpha_as_tao"),
            "total_bought_alpha_as_usd": obj.get("total_bought_alpha_as_usd"),
            "total_buys": obj.get("total_buys"),
            "total_earned_alpha": obj.get("total_earned_alpha"),
            "total_earned_alpha_as_tao": obj.get("total_earned_alpha_as_tao"),
            "total_earned_alpha_as_usd": obj.get("total_earned_alpha_as_usd"),
            "total_sells": obj.get("total_sells"),
            "total_sold_alpha": obj.get("total_sold_alpha"),
            "total_sold_alpha_as_tao": obj.get("total_sold_alpha_as_tao"),
            "total_sold_alpha_as_usd": obj.get("total_sold_alpha_as_usd"),
            "total_transferred_in_alpha": obj.get("total_transferred_in_alpha"),
            "total_transferred_in_alpha_as_tao": obj.get("total_transferred_in_alpha_as_tao"),
            "total_transferred_in_alpha_as_usd": obj.get("total_transferred_in_alpha_as_usd"),
            "total_transferred_out_alpha": obj.get("total_transferred_out_alpha"),
            "total_transferred_out_alpha_as_tao": obj.get("total_transferred_out_alpha_as_tao"),
            "total_transferred_out_alpha_as_usd": obj.get("total_transferred_out_alpha_as_usd"),
            "total_transfers_in": obj.get("total_transfers_in"),
            "total_transfers_out": obj.get("total_transfers_out"),
            "unrealised_profit_tao": obj.get("unrealised_profit_tao"),
            "unrealised_profit_usd": obj.get("unrealised_profit_usd")
        })
        return _obj


