# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.dtao_validator_yield_latest_order import DtaoValidatorYieldLatestOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoValidatorYieldLatestRequest(BaseModel):
    """
    DtaoValidatorYieldLatestRequest
    """ # noqa: E501
    hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    limit: Optional[int] = None
    min_stake: Optional[StrictStr] = None
    netuid: Optional[int] = None
    order: Optional[DtaoValidatorYieldLatestOrder] = None
    page: Optional[int] = None
    __properties: ClassVar[List[str]] = ["hotkey", "limit", "min_stake", "netuid", "order", "page"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorYieldLatestRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        # set to None if min_stake (nullable) is None
        # and model_fields_set contains the field
        if self.min_stake is None and "min_stake" in self.model_fields_set:
            _dict['min_stake'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoValidatorYieldLatestRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hotkey": obj.get("hotkey"),
            "limit": obj.get("limit"),
            "min_stake": obj.get("min_stake"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page")
        })
        return _obj


