# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class DtaoValidatorPerformanceLatestOrder(str, Enum):
    """
    DtaoValidatorPerformanceLatestOrder
    """

    """
    allowed enum values
    """
    NETUID_ASC = 'netuid_asc'
    NETUID_DESC = 'netuid_desc'
    UID_ASC = 'uid_asc'
    UID_DESC = 'uid_desc'
    NOMINATORS_ASC = 'nominators_asc'
    NOMINATORS_DESC = 'nominators_desc'
    POSITION_ASC = 'position_asc'
    POSITION_DESC = 'position_desc'
    LAST_UPDATED_ASC = 'last_updated_asc'
    LAST_UPDATED_DESC = 'last_updated_desc'
    V_TRUST_ASC = 'v_trust_asc'
    V_TRUST_DESC = 'v_trust_desc'
    TYPE_ASC = 'type_asc'
    TYPE_DESC = 'type_desc'
    TAKE_ASC = 'take_asc'
    TAKE_DESC = 'take_desc'
    CHILDKEY_TAKE_ASC = 'childkey_take_asc'
    CHILDKEY_TAKE_DESC = 'childkey_take_desc'
    PROPORTION_ASC = 'proportion_asc'
    PROPORTION_DESC = 'proportion_desc'
    SUBNET_WEIGHT_ASC = 'subnet_weight_asc'
    SUBNET_WEIGHT_DESC = 'subnet_weight_desc'
    ROOT_WEIGHT_ASC = 'root_weight_asc'
    ROOT_WEIGHT_DESC = 'root_weight_desc'
    ALPHA_ASC = 'alpha_asc'
    ALPHA_DESC = 'alpha_desc'
    FAMILY_SUBNET_WEIGHT_ASC = 'family_subnet_weight_asc'
    FAMILY_SUBNET_WEIGHT_DESC = 'family_subnet_weight_desc'
    FAMILY_ROOT_WEIGHT_ASC = 'family_root_weight_asc'
    FAMILY_ROOT_WEIGHT_DESC = 'family_root_weight_desc'
    FAMILY_ALPHA_ASC = 'family_alpha_asc'
    FAMILY_ALPHA_DESC = 'family_alpha_desc'
    DOMINANCE_ASC = 'dominance_asc'
    DOMINANCE_DESC = 'dominance_desc'
    DIVIDENDS_ASC = 'dividends_asc'
    DIVIDENDS_DESC = 'dividends_desc'
    RATIO_ASC = 'ratio_asc'
    RATIO_DESC = 'ratio_desc'
    NOMINATOR_RETURN_PER_DAY_ASC = 'nominator_return_per_day_asc'
    NOMINATOR_RETURN_PER_DAY_DESC = 'nominator_return_per_day_desc'
    VALIDATOR_RETURN_PER_DAY_ASC = 'validator_return_per_day_asc'
    VALIDATOR_RETURN_PER_DAY_DESC = 'validator_return_per_day_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoValidatorPerformanceLatestOrder from a JSON string"""
        return cls(json.loads(json_str))


