# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.dtao_liquidity_position_event_order import DtaoLiquidityPositionEventOrder
from openapi_server.models.liquidity_position_type import LiquidityPositionType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class DtaoLiquidityPositionEventRequest(BaseModel):
    """
    DtaoLiquidityPositionEventRequest
    """ # noqa: E501
    coldkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    id: Optional[StrictStr] = None
    limit: Optional[int] = None
    netuid: Optional[int] = None
    order: Optional[DtaoLiquidityPositionEventOrder] = None
    page: Optional[int] = None
    position_id: Optional[StrictStr] = None
    position_type: Optional[LiquidityPositionType] = None
    __properties: ClassVar[List[str]] = ["coldkey", "id", "limit", "netuid", "order", "page", "position_id", "position_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DtaoLiquidityPositionEventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if coldkey (nullable) is None
        # and model_fields_set contains the field
        if self.coldkey is None and "coldkey" in self.model_fields_set:
            _dict['coldkey'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if position_id (nullable) is None
        # and model_fields_set contains the field
        if self.position_id is None and "position_id" in self.model_fields_set:
            _dict['position_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of DtaoLiquidityPositionEventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coldkey": obj.get("coldkey"),
            "id": obj.get("id"),
            "limit": obj.get("limit"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "position_id": obj.get("position_id"),
            "position_type": obj.get("position_type")
        })
        return _obj


