# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.event_order import EventOrder
from openapi_server.models.network import Network
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EventRequest(BaseModel):
    """
    EventRequest
    """ # noqa: E501
    block_end: Optional[int] = Field(default=None, description="End of block range (inclusive)")
    block_number: Optional[int] = None
    block_start: Optional[int] = Field(default=None, description="Start of block range (inclusive)")
    call_id: Optional[StrictStr] = None
    extrinsic_id: Optional[StrictStr] = None
    full_name: Optional[StrictStr] = Field(default=None, description="Full name of the event, e.g. \"SubtensorModule.AxonServed\"")
    id: Optional[StrictStr] = None
    limit: Optional[int] = None
    name: Optional[StrictStr] = None
    network: Optional[Network] = None
    order: Optional[EventOrder] = None
    page: Optional[int] = None
    pallet: Optional[StrictStr] = None
    phase: Optional[StrictStr] = None
    timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    __properties: ClassVar[List[str]] = ["block_end", "block_number", "block_start", "call_id", "extrinsic_id", "full_name", "id", "limit", "name", "network", "order", "page", "pallet", "phase", "timestamp_end", "timestamp_start"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_number (nullable) is None
        # and model_fields_set contains the field
        if self.block_number is None and "block_number" in self.model_fields_set:
            _dict['block_number'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if call_id (nullable) is None
        # and model_fields_set contains the field
        if self.call_id is None and "call_id" in self.model_fields_set:
            _dict['call_id'] = None

        # set to None if extrinsic_id (nullable) is None
        # and model_fields_set contains the field
        if self.extrinsic_id is None and "extrinsic_id" in self.model_fields_set:
            _dict['extrinsic_id'] = None

        # set to None if full_name (nullable) is None
        # and model_fields_set contains the field
        if self.full_name is None and "full_name" in self.model_fields_set:
            _dict['full_name'] = None

        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if pallet (nullable) is None
        # and model_fields_set contains the field
        if self.pallet is None and "pallet" in self.model_fields_set:
            _dict['pallet'] = None

        # set to None if phase (nullable) is None
        # and model_fields_set contains the field
        if self.phase is None and "phase" in self.model_fields_set:
            _dict['phase'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_end": obj.get("block_end"),
            "block_number": obj.get("block_number"),
            "block_start": obj.get("block_start"),
            "call_id": obj.get("call_id"),
            "extrinsic_id": obj.get("extrinsic_id"),
            "full_name": obj.get("full_name"),
            "id": obj.get("id"),
            "limit": obj.get("limit"),
            "name": obj.get("name"),
            "network": obj.get("network"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "pallet": obj.get("pallet"),
            "phase": obj.get("phase"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start")
        })
        return _obj


