# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.evm_log_order import EVMLogOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMLogRequest(BaseModel):
    """
    EVMLogRequest
    """ # noqa: E501
    address: Optional[StrictStr] = None
    block_end: Optional[int] = Field(default=None, description="End of block range (inclusive)")
    block_number: Optional[int] = None
    block_start: Optional[int] = Field(default=None, description="Start of block range (inclusive)")
    event_name: Optional[StrictStr] = None
    limit: Optional[int] = None
    order: Optional[EVMLogOrder] = None
    page: Optional[int] = None
    timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    topic0: Optional[StrictStr] = None
    transaction_hash: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "block_end", "block_number", "block_start", "event_name", "limit", "order", "page", "timestamp_end", "timestamp_start", "topic0", "transaction_hash"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMLogRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_number (nullable) is None
        # and model_fields_set contains the field
        if self.block_number is None and "block_number" in self.model_fields_set:
            _dict['block_number'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if event_name (nullable) is None
        # and model_fields_set contains the field
        if self.event_name is None and "event_name" in self.model_fields_set:
            _dict['event_name'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        # set to None if topic0 (nullable) is None
        # and model_fields_set contains the field
        if self.topic0 is None and "topic0" in self.model_fields_set:
            _dict['topic0'] = None

        # set to None if transaction_hash (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_hash is None and "transaction_hash" in self.model_fields_set:
            _dict['transaction_hash'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMLogRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "block_end": obj.get("block_end"),
            "block_number": obj.get("block_number"),
            "block_start": obj.get("block_start"),
            "event_name": obj.get("event_name"),
            "limit": obj.get("limit"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start"),
            "topic0": obj.get("topic0"),
            "transaction_hash": obj.get("transaction_hash")
        })
        return _obj


