# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMContractItem(BaseModel):
    """
    EVMContractItem
    """ # noqa: E501
    abi: Optional[Any] = None
    address: StrictStr
    block_number: int
    created_by: StrictStr
    decimals: Optional[int] = None
    erc1155: StrictBool
    erc165: StrictBool
    erc20: StrictBool
    erc721: StrictBool
    input: StrictStr
    name: Optional[StrictStr] = None
    owner: Optional[StrictStr] = None
    symbol: Optional[StrictStr] = None
    timestamp: datetime
    transaction_hash: StrictStr
    uniswap_v2: StrictBool
    uniswap_v3: StrictBool
    __properties: ClassVar[List[str]] = ["abi", "address", "block_number", "created_by", "decimals", "erc1155", "erc165", "erc20", "erc721", "input", "name", "owner", "symbol", "timestamp", "transaction_hash", "uniswap_v2", "uniswap_v3"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMContractItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if abi (nullable) is None
        # and model_fields_set contains the field
        if self.abi is None and "abi" in self.model_fields_set:
            _dict['abi'] = None

        # set to None if decimals (nullable) is None
        # and model_fields_set contains the field
        if self.decimals is None and "decimals" in self.model_fields_set:
            _dict['decimals'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        # set to None if symbol (nullable) is None
        # and model_fields_set contains the field
        if self.symbol is None and "symbol" in self.model_fields_set:
            _dict['symbol'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMContractItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "abi": obj.get("abi"),
            "address": obj.get("address"),
            "block_number": obj.get("block_number"),
            "created_by": obj.get("created_by"),
            "decimals": obj.get("decimals"),
            "erc1155": obj.get("erc1155"),
            "erc165": obj.get("erc165"),
            "erc20": obj.get("erc20"),
            "erc721": obj.get("erc721"),
            "input": obj.get("input"),
            "name": obj.get("name"),
            "owner": obj.get("owner"),
            "symbol": obj.get("symbol"),
            "timestamp": obj.get("timestamp"),
            "transaction_hash": obj.get("transaction_hash"),
            "uniswap_v2": obj.get("uniswap_v2"),
            "uniswap_v3": obj.get("uniswap_v3")
        })
        return _obj


