# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMTransactionItem(BaseModel):
    """
    EVMTransactionItem
    """ # noqa: E501
    abi_json: Optional[Any] = None
    args: Optional[Any] = None
    block_hash: StrictStr
    block_number: int
    contract_created: Optional[StrictStr] = None
    cumulative_gas_used: StrictStr
    effective_gas_price: StrictStr
    var_from: StrictStr = Field(alias="from")
    full_signature: Optional[StrictStr] = None
    gas: StrictStr
    gas_price: StrictStr
    gas_used: StrictStr
    hash: StrictStr
    hashable_signature: Optional[StrictStr] = None
    index: int
    input: StrictStr
    max_fee_per_gas: Optional[StrictStr] = None
    max_priority_fee_per_gas: Optional[StrictStr] = None
    method_id: Optional[StrictStr] = None
    method_name: Optional[StrictStr] = None
    nonce: int
    success: StrictBool
    timestamp: datetime
    to: Optional[StrictStr] = None
    value: StrictStr
    __properties: ClassVar[List[str]] = ["abi_json", "args", "block_hash", "block_number", "contract_created", "cumulative_gas_used", "effective_gas_price", "from", "full_signature", "gas", "gas_price", "gas_used", "hash", "hashable_signature", "index", "input", "max_fee_per_gas", "max_priority_fee_per_gas", "method_id", "method_name", "nonce", "success", "timestamp", "to", "value"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMTransactionItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if abi_json (nullable) is None
        # and model_fields_set contains the field
        if self.abi_json is None and "abi_json" in self.model_fields_set:
            _dict['abi_json'] = None

        # set to None if args (nullable) is None
        # and model_fields_set contains the field
        if self.args is None and "args" in self.model_fields_set:
            _dict['args'] = None

        # set to None if contract_created (nullable) is None
        # and model_fields_set contains the field
        if self.contract_created is None and "contract_created" in self.model_fields_set:
            _dict['contract_created'] = None

        # set to None if full_signature (nullable) is None
        # and model_fields_set contains the field
        if self.full_signature is None and "full_signature" in self.model_fields_set:
            _dict['full_signature'] = None

        # set to None if hashable_signature (nullable) is None
        # and model_fields_set contains the field
        if self.hashable_signature is None and "hashable_signature" in self.model_fields_set:
            _dict['hashable_signature'] = None

        # set to None if max_fee_per_gas (nullable) is None
        # and model_fields_set contains the field
        if self.max_fee_per_gas is None and "max_fee_per_gas" in self.model_fields_set:
            _dict['max_fee_per_gas'] = None

        # set to None if max_priority_fee_per_gas (nullable) is None
        # and model_fields_set contains the field
        if self.max_priority_fee_per_gas is None and "max_priority_fee_per_gas" in self.model_fields_set:
            _dict['max_priority_fee_per_gas'] = None

        # set to None if method_id (nullable) is None
        # and model_fields_set contains the field
        if self.method_id is None and "method_id" in self.model_fields_set:
            _dict['method_id'] = None

        # set to None if method_name (nullable) is None
        # and model_fields_set contains the field
        if self.method_name is None and "method_name" in self.model_fields_set:
            _dict['method_name'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMTransactionItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "abi_json": obj.get("abi_json"),
            "args": obj.get("args"),
            "block_hash": obj.get("block_hash"),
            "block_number": obj.get("block_number"),
            "contract_created": obj.get("contract_created"),
            "cumulative_gas_used": obj.get("cumulative_gas_used"),
            "effective_gas_price": obj.get("effective_gas_price"),
            "from": obj.get("from"),
            "full_signature": obj.get("full_signature"),
            "gas": obj.get("gas"),
            "gas_price": obj.get("gas_price"),
            "gas_used": obj.get("gas_used"),
            "hash": obj.get("hash"),
            "hashable_signature": obj.get("hashable_signature"),
            "index": obj.get("index"),
            "input": obj.get("input"),
            "max_fee_per_gas": obj.get("max_fee_per_gas"),
            "max_priority_fee_per_gas": obj.get("max_priority_fee_per_gas"),
            "method_id": obj.get("method_id"),
            "method_name": obj.get("method_name"),
            "nonce": obj.get("nonce"),
            "success": obj.get("success"),
            "timestamp": obj.get("timestamp"),
            "to": obj.get("to"),
            "value": obj.get("value")
        })
        return _obj


