# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMERC20TransferItem(BaseModel):
    """
    EVMERC20TransferItem
    """ # noqa: E501
    amount: StrictStr
    block_number: int
    var_from: StrictStr = Field(alias="from")
    timestamp: datetime
    to: StrictStr
    token_address: StrictStr
    token_decimals: int
    token_name: StrictStr
    token_symbol: StrictStr
    transaction_hash: StrictStr
    __properties: ClassVar[List[str]] = ["amount", "block_number", "from", "timestamp", "to", "token_address", "token_decimals", "token_name", "token_symbol", "transaction_hash"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMERC20TransferItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMERC20TransferItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "block_number": obj.get("block_number"),
            "from": obj.get("from"),
            "timestamp": obj.get("timestamp"),
            "to": obj.get("to"),
            "token_address": obj.get("token_address"),
            "token_decimals": obj.get("token_decimals"),
            "token_name": obj.get("token_name"),
            "token_symbol": obj.get("token_symbol"),
            "transaction_hash": obj.get("transaction_hash")
        })
        return _obj


