# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class EVMERC20AccountOrder(str, Enum):
    """
    EVMERC20AccountOrder
    """

    """
    allowed enum values
    """
    LAST_ACTIVE_BLOCK_NUMBER_ASC = 'last_active_block_number_asc'
    LAST_ACTIVE_BLOCK_NUMBER_DESC = 'last_active_block_number_desc'
    LAST_ACTIVE_TIMESTAMP_ASC = 'last_active_timestamp_asc'
    LAST_ACTIVE_TIMESTAMP_DESC = 'last_active_timestamp_desc'
    FIRST_ACTIVE_BLOCK_NUMBER_ASC = 'first_active_block_number_asc'
    FIRST_ACTIVE_BLOCK_NUMBER_DESC = 'first_active_block_number_desc'
    FIRST_ACTIVE_TIMESTAMP_ASC = 'first_active_timestamp_asc'
    FIRST_ACTIVE_TIMESTAMP_DESC = 'first_active_timestamp_desc'
    BALANCE_ASC = 'balance_asc'
    BALANCE_DESC = 'balance_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMERC20AccountOrder from a JSON string"""
        return cls(json.loads(json_str))


