# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.evmerc20_account_order import EVMERC20AccountOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMERC20AccountRequest(BaseModel):
    """
    EVMERC20AccountRequest
    """ # noqa: E501
    address: Optional[StrictStr] = None
    balance_max: Optional[StrictStr] = Field(default=None, description="Maximum balance (inclusive)")
    balance_min: Optional[StrictStr] = Field(default=None, description="Minimum balance (inclusive)")
    limit: Optional[int] = None
    order: Optional[EVMERC20AccountOrder] = None
    page: Optional[int] = None
    token_address: Optional[StrictStr] = None
    token_name: Optional[StrictStr] = None
    token_symbol: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "balance_max", "balance_min", "limit", "order", "page", "token_address", "token_name", "token_symbol"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMERC20AccountRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if balance_max (nullable) is None
        # and model_fields_set contains the field
        if self.balance_max is None and "balance_max" in self.model_fields_set:
            _dict['balance_max'] = None

        # set to None if balance_min (nullable) is None
        # and model_fields_set contains the field
        if self.balance_min is None and "balance_min" in self.model_fields_set:
            _dict['balance_min'] = None

        # set to None if token_address (nullable) is None
        # and model_fields_set contains the field
        if self.token_address is None and "token_address" in self.model_fields_set:
            _dict['token_address'] = None

        # set to None if token_name (nullable) is None
        # and model_fields_set contains the field
        if self.token_name is None and "token_name" in self.model_fields_set:
            _dict['token_name'] = None

        # set to None if token_symbol (nullable) is None
        # and model_fields_set contains the field
        if self.token_symbol is None and "token_symbol" in self.model_fields_set:
            _dict['token_symbol'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMERC20AccountRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "balance_max": obj.get("balance_max"),
            "balance_min": obj.get("balance_min"),
            "limit": obj.get("limit"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "token_address": obj.get("token_address"),
            "token_name": obj.get("token_name"),
            "token_symbol": obj.get("token_symbol")
        })
        return _obj


