# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.evmerc20_transfer_order import EVMERC20TransferOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class EVMERC20TransferRequest(BaseModel):
    """
    EVMERC20TransferRequest
    """ # noqa: E501
    address: Optional[StrictStr] = None
    amount_max: Optional[StrictStr] = Field(default=None, description="Maximum amount (inclusive)")
    amount_min: Optional[StrictStr] = Field(default=None, description="Minimum amount (inclusive)")
    block_end: Optional[int] = Field(default=None, description="End of block range (inclusive)")
    block_number: Optional[int] = None
    block_start: Optional[int] = Field(default=None, description="Start of block range (inclusive)")
    var_from: Optional[StrictStr] = Field(default=None, alias="from")
    limit: Optional[int] = None
    order: Optional[EVMERC20TransferOrder] = None
    page: Optional[int] = None
    timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    to: Optional[StrictStr] = None
    token_address: Optional[StrictStr] = None
    token_name: Optional[StrictStr] = None
    token_symbol: Optional[StrictStr] = None
    transaction_hash: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["address", "amount_max", "amount_min", "block_end", "block_number", "block_start", "from", "limit", "order", "page", "timestamp_end", "timestamp_start", "to", "token_address", "token_name", "token_symbol", "transaction_hash"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EVMERC20TransferRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if amount_max (nullable) is None
        # and model_fields_set contains the field
        if self.amount_max is None and "amount_max" in self.model_fields_set:
            _dict['amount_max'] = None

        # set to None if amount_min (nullable) is None
        # and model_fields_set contains the field
        if self.amount_min is None and "amount_min" in self.model_fields_set:
            _dict['amount_min'] = None

        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_number (nullable) is None
        # and model_fields_set contains the field
        if self.block_number is None and "block_number" in self.model_fields_set:
            _dict['block_number'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        # set to None if token_address (nullable) is None
        # and model_fields_set contains the field
        if self.token_address is None and "token_address" in self.model_fields_set:
            _dict['token_address'] = None

        # set to None if token_name (nullable) is None
        # and model_fields_set contains the field
        if self.token_name is None and "token_name" in self.model_fields_set:
            _dict['token_name'] = None

        # set to None if token_symbol (nullable) is None
        # and model_fields_set contains the field
        if self.token_symbol is None and "token_symbol" in self.model_fields_set:
            _dict['token_symbol'] = None

        # set to None if transaction_hash (nullable) is None
        # and model_fields_set contains the field
        if self.transaction_hash is None and "transaction_hash" in self.model_fields_set:
            _dict['transaction_hash'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of EVMERC20TransferRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "amount_max": obj.get("amount_max"),
            "amount_min": obj.get("amount_min"),
            "block_end": obj.get("block_end"),
            "block_number": obj.get("block_number"),
            "block_start": obj.get("block_start"),
            "from": obj.get("from"),
            "limit": obj.get("limit"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start"),
            "to": obj.get("to"),
            "token_address": obj.get("token_address"),
            "token_name": obj.get("token_name"),
            "token_symbol": obj.get("token_symbol"),
            "transaction_hash": obj.get("transaction_hash")
        })
        return _obj


