# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExtrinsicItem(BaseModel):
    """
    ExtrinsicItem
    """ # noqa: E501
    block_number: int
    call_args: Optional[Any] = None
    call_id: Optional[StrictStr] = None
    error: Optional[Any] = None
    fee: Optional[StrictStr] = None
    full_name: StrictStr
    hash: StrictStr
    id: StrictStr
    index: int
    signature: Optional[Any] = None
    signer_address: Optional[StrictStr] = None
    success: Optional[StrictBool] = None
    timestamp: datetime
    tip: Optional[StrictStr] = None
    version: int
    __properties: ClassVar[List[str]] = ["block_number", "call_args", "call_id", "error", "fee", "full_name", "hash", "id", "index", "signature", "signer_address", "success", "timestamp", "tip", "version"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExtrinsicItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if call_args (nullable) is None
        # and model_fields_set contains the field
        if self.call_args is None and "call_args" in self.model_fields_set:
            _dict['call_args'] = None

        # set to None if call_id (nullable) is None
        # and model_fields_set contains the field
        if self.call_id is None and "call_id" in self.model_fields_set:
            _dict['call_id'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if signature (nullable) is None
        # and model_fields_set contains the field
        if self.signature is None and "signature" in self.model_fields_set:
            _dict['signature'] = None

        # set to None if signer_address (nullable) is None
        # and model_fields_set contains the field
        if self.signer_address is None and "signer_address" in self.model_fields_set:
            _dict['signer_address'] = None

        # set to None if success (nullable) is None
        # and model_fields_set contains the field
        if self.success is None and "success" in self.model_fields_set:
            _dict['success'] = None

        # set to None if tip (nullable) is None
        # and model_fields_set contains the field
        if self.tip is None and "tip" in self.model_fields_set:
            _dict['tip'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExtrinsicItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "call_args": obj.get("call_args"),
            "call_id": obj.get("call_id"),
            "error": obj.get("error"),
            "fee": obj.get("fee"),
            "full_name": obj.get("full_name"),
            "hash": obj.get("hash"),
            "id": obj.get("id"),
            "index": obj.get("index"),
            "signature": obj.get("signature"),
            "signer_address": obj.get("signer_address"),
            "success": obj.get("success"),
            "timestamp": obj.get("timestamp"),
            "tip": obj.get("tip"),
            "version": obj.get("version")
        })
        return _obj


