# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HistoryResponse(BaseModel):
    """
    HistoryResponse
    """ # noqa: E501
    c: Optional[List[Union[StrictFloat]]] = None
    h: Optional[List[Union[StrictFloat]]] = None
    l: Optional[List[Union[StrictFloat]]] = None
    next_time: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="nextTime")
    o: Optional[List[Union[StrictFloat]]] = None
    s: StrictStr
    t: Optional[List[Annotated[int, Field(strict=True, ge=0)]]] = None
    v: Optional[List[Union[StrictFloat]]] = None
    __properties: ClassVar[List[str]] = ["c", "h", "l", "nextTime", "o", "s", "t", "v"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HistoryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if c (nullable) is None
        # and model_fields_set contains the field
        if self.c is None and "c" in self.model_fields_set:
            _dict['c'] = None

        # set to None if h (nullable) is None
        # and model_fields_set contains the field
        if self.h is None and "h" in self.model_fields_set:
            _dict['h'] = None

        # set to None if l (nullable) is None
        # and model_fields_set contains the field
        if self.l is None and "l" in self.model_fields_set:
            _dict['l'] = None

        # set to None if next_time (nullable) is None
        # and model_fields_set contains the field
        if self.next_time is None and "next_time" in self.model_fields_set:
            _dict['nextTime'] = None

        # set to None if o (nullable) is None
        # and model_fields_set contains the field
        if self.o is None and "o" in self.model_fields_set:
            _dict['o'] = None

        # set to None if t (nullable) is None
        # and model_fields_set contains the field
        if self.t is None and "t" in self.model_fields_set:
            _dict['t'] = None

        # set to None if v (nullable) is None
        # and model_fields_set contains the field
        if self.v is None and "v" in self.model_fields_set:
            _dict['v'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HistoryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "c": obj.get("c"),
            "h": obj.get("h"),
            "l": obj.get("l"),
            "nextTime": obj.get("nextTime"),
            "o": obj.get("o"),
            "s": obj.get("s"),
            "t": obj.get("t"),
            "v": obj.get("v")
        })
        return _obj


