# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HotkeyRelation(BaseModel):
    """
    HotkeyRelation
    """ # noqa: E501
    alpha_stake: StrictStr
    childkey_take: StrictStr
    coldkey: Key
    family_alpha_stake: StrictStr
    family_root_stake: StrictStr
    family_root_stake_as_alpha: StrictStr
    family_stake: StrictStr = Field(description="Total stake including parent/child relationships")
    family_total_alpha_stake: StrictStr
    hotkey: Key
    proportion: StrictStr = Field(description="The proportion of the stake given to the child")
    proportion_alpha_stake: StrictStr
    proportion_root_stake: StrictStr
    proportion_root_stake_as_alpha: StrictStr
    proportion_staked: StrictStr = Field(description="The stake given to the child")
    proportion_total_alpha_stake: StrictStr
    root_stake: StrictStr
    root_stake_as_alpha: StrictStr
    root_weight: StrictStr
    stake: StrictStr = Field(description="Total stake excluding parent/child relationships")
    take: StrictStr
    total_alpha_stake: StrictStr
    __properties: ClassVar[List[str]] = ["alpha_stake", "childkey_take", "coldkey", "family_alpha_stake", "family_root_stake", "family_root_stake_as_alpha", "family_stake", "family_total_alpha_stake", "hotkey", "proportion", "proportion_alpha_stake", "proportion_root_stake", "proportion_root_stake_as_alpha", "proportion_staked", "proportion_total_alpha_stake", "root_stake", "root_stake_as_alpha", "root_weight", "stake", "take", "total_alpha_stake"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HotkeyRelation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HotkeyRelation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_stake": obj.get("alpha_stake"),
            "childkey_take": obj.get("childkey_take"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "family_alpha_stake": obj.get("family_alpha_stake"),
            "family_root_stake": obj.get("family_root_stake"),
            "family_root_stake_as_alpha": obj.get("family_root_stake_as_alpha"),
            "family_stake": obj.get("family_stake"),
            "family_total_alpha_stake": obj.get("family_total_alpha_stake"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "proportion": obj.get("proportion"),
            "proportion_alpha_stake": obj.get("proportion_alpha_stake"),
            "proportion_root_stake": obj.get("proportion_root_stake"),
            "proportion_root_stake_as_alpha": obj.get("proportion_root_stake_as_alpha"),
            "proportion_staked": obj.get("proportion_staked"),
            "proportion_total_alpha_stake": obj.get("proportion_total_alpha_stake"),
            "root_stake": obj.get("root_stake"),
            "root_stake_as_alpha": obj.get("root_stake_as_alpha"),
            "root_weight": obj.get("root_weight"),
            "stake": obj.get("stake"),
            "take": obj.get("take"),
            "total_alpha_stake": obj.get("total_alpha_stake")
        })
        return _obj


