# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class HotkeyItem(BaseModel):
    """
    HotkeyItem
    """ # noqa: E501
    alpha_balance: StrictStr
    alpha_balance_as_tao: StrictStr
    axon: StrictStr
    coldkey: Key
    consensus: StrictStr
    deregistered: StrictBool
    deregistration_timestamp: Optional[datetime] = None
    emission: StrictStr
    hotkey: Key
    immune: StrictBool
    in_danger: StrictBool
    incentive: StrictStr
    mech_incentive: List[StrictStr]
    miner_rank: Optional[int] = None
    netuid: int
    registration_block: int
    total_emission: StrictStr
    total_emission_as_tao: StrictStr
    trust: StrictStr
    uid: int
    validator_rank: Optional[int] = None
    __properties: ClassVar[List[str]] = ["alpha_balance", "alpha_balance_as_tao", "axon", "coldkey", "consensus", "deregistered", "deregistration_timestamp", "emission", "hotkey", "immune", "in_danger", "incentive", "mech_incentive", "miner_rank", "netuid", "registration_block", "total_emission", "total_emission_as_tao", "trust", "uid", "validator_rank"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HotkeyItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if deregistration_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.deregistration_timestamp is None and "deregistration_timestamp" in self.model_fields_set:
            _dict['deregistration_timestamp'] = None

        # set to None if miner_rank (nullable) is None
        # and model_fields_set contains the field
        if self.miner_rank is None and "miner_rank" in self.model_fields_set:
            _dict['miner_rank'] = None

        # set to None if validator_rank (nullable) is None
        # and model_fields_set contains the field
        if self.validator_rank is None and "validator_rank" in self.model_fields_set:
            _dict['validator_rank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of HotkeyItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_balance": obj.get("alpha_balance"),
            "alpha_balance_as_tao": obj.get("alpha_balance_as_tao"),
            "axon": obj.get("axon"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "consensus": obj.get("consensus"),
            "deregistered": obj.get("deregistered"),
            "deregistration_timestamp": obj.get("deregistration_timestamp"),
            "emission": obj.get("emission"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "immune": obj.get("immune"),
            "in_danger": obj.get("in_danger"),
            "incentive": obj.get("incentive"),
            "mech_incentive": obj.get("mech_incentive"),
            "miner_rank": obj.get("miner_rank"),
            "netuid": obj.get("netuid"),
            "registration_block": obj.get("registration_block"),
            "total_emission": obj.get("total_emission"),
            "total_emission_as_tao": obj.get("total_emission_as_tao"),
            "trust": obj.get("trust"),
            "uid": obj.get("uid"),
            "validator_rank": obj.get("validator_rank")
        })
        return _obj


