# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IdentityHistoryItem(BaseModel):
    """
    IdentityHistoryItem
    """ # noqa: E501
    additional: Optional[StrictStr] = None
    address: Key
    block_number: int
    description: Optional[StrictStr] = None
    discord: Optional[StrictStr] = None
    github_repo: Optional[StrictStr] = None
    image: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    timestamp: datetime
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["additional", "address", "block_number", "description", "discord", "github_repo", "image", "name", "timestamp", "url"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IdentityHistoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # set to None if additional (nullable) is None
        # and model_fields_set contains the field
        if self.additional is None and "additional" in self.model_fields_set:
            _dict['additional'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if discord (nullable) is None
        # and model_fields_set contains the field
        if self.discord is None and "discord" in self.model_fields_set:
            _dict['discord'] = None

        # set to None if github_repo (nullable) is None
        # and model_fields_set contains the field
        if self.github_repo is None and "github_repo" in self.model_fields_set:
            _dict['github_repo'] = None

        # set to None if image (nullable) is None
        # and model_fields_set contains the field
        if self.image is None and "image" in self.model_fields_set:
            _dict['image'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IdentityHistoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additional": obj.get("additional"),
            "address": Key.from_dict(obj.get("address")) if obj.get("address") is not None else None,
            "block_number": obj.get("block_number"),
            "description": obj.get("description"),
            "discord": obj.get("discord"),
            "github_repo": obj.get("github_repo"),
            "image": obj.get("image"),
            "name": obj.get("name"),
            "timestamp": obj.get("timestamp"),
            "url": obj.get("url")
        })
        return _obj


