# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.metagraph_order import MetagraphOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MetagraphRequest(BaseModel):
    """
    MetagraphRequest
    """ # noqa: E501
    active: Optional[StrictBool] = None
    coldkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    is_child_key: Optional[StrictBool] = None
    is_immunity_period: Optional[StrictBool] = None
    limit: Optional[int] = None
    netuid: Optional[int] = Field(default=None, description="Subnet ID")
    order: Optional[MetagraphOrder] = None
    page: Optional[int] = None
    search: Optional[StrictStr] = Field(default=None, description="Search across UID, hotkey, coldkey, axon_ip")
    uid: Optional[int] = Field(default=None, description="Neuron ID")
    validator_permit: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["active", "coldkey", "hotkey", "is_child_key", "is_immunity_period", "limit", "netuid", "order", "page", "search", "uid", "validator_permit"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MetagraphRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if active (nullable) is None
        # and model_fields_set contains the field
        if self.active is None and "active" in self.model_fields_set:
            _dict['active'] = None

        # set to None if coldkey (nullable) is None
        # and model_fields_set contains the field
        if self.coldkey is None and "coldkey" in self.model_fields_set:
            _dict['coldkey'] = None

        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        # set to None if is_child_key (nullable) is None
        # and model_fields_set contains the field
        if self.is_child_key is None and "is_child_key" in self.model_fields_set:
            _dict['is_child_key'] = None

        # set to None if is_immunity_period (nullable) is None
        # and model_fields_set contains the field
        if self.is_immunity_period is None and "is_immunity_period" in self.model_fields_set:
            _dict['is_immunity_period'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if search (nullable) is None
        # and model_fields_set contains the field
        if self.search is None and "search" in self.model_fields_set:
            _dict['search'] = None

        # set to None if uid (nullable) is None
        # and model_fields_set contains the field
        if self.uid is None and "uid" in self.model_fields_set:
            _dict['uid'] = None

        # set to None if validator_permit (nullable) is None
        # and model_fields_set contains the field
        if self.validator_permit is None and "validator_permit" in self.model_fields_set:
            _dict['validator_permit'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MetagraphRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "coldkey": obj.get("coldkey"),
            "hotkey": obj.get("hotkey"),
            "is_child_key": obj.get("is_child_key"),
            "is_immunity_period": obj.get("is_immunity_period"),
            "limit": obj.get("limit"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "search": obj.get("search"),
            "uid": obj.get("uid"),
            "validator_permit": obj.get("validator_permit")
        })
        return _obj


