# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class MetagraphOrder(str, Enum):
    """
    MetagraphOrder
    """

    """
    allowed enum values
    """
    UPDATED_ASC = 'updated_asc'
    UPDATED_DESC = 'updated_desc'
    UID_ASC = 'uid_asc'
    UID_DESC = 'uid_desc'
    STAKE_ASC = 'stake_asc'
    STAKE_DESC = 'stake_desc'
    TRUST_ASC = 'trust_asc'
    TRUST_DESC = 'trust_desc'
    VALIDATOR_TRUST_ASC = 'validator_trust_asc'
    VALIDATOR_TRUST_DESC = 'validator_trust_desc'
    CONSENSUS_ASC = 'consensus_asc'
    CONSENSUS_DESC = 'consensus_desc'
    INCENTIVE_ASC = 'incentive_asc'
    INCENTIVE_DESC = 'incentive_desc'
    DIVIDENDS_ASC = 'dividends_asc'
    DIVIDENDS_DESC = 'dividends_desc'
    EMISSION_ASC = 'emission_asc'
    EMISSION_DESC = 'emission_desc'
    ACTIVE_ASC = 'active_asc'
    ACTIVE_DESC = 'active_desc'
    HOTKEY_ASC = 'hotkey_asc'
    HOTKEY_DESC = 'hotkey_desc'
    COLDKEY_ASC = 'coldkey_asc'
    COLDKEY_DESC = 'coldkey_desc'
    VALIDATOR_PERMIT_ASC = 'validator_permit_asc'
    VALIDATOR_PERMIT_DESC = 'validator_permit_desc'
    AXON_ASC = 'axon_asc'
    AXON_DESC = 'axon_desc'
    DAILY_REWARD_ASC = 'daily_reward_asc'
    DAILY_REWARD_DESC = 'daily_reward_desc'
    REGISTERED_AT_ASC = 'registered_at_asc'
    REGISTERED_AT_DESC = 'registered_at_desc'
    IS_IMMUNITY_PERIOD_ASC = 'is_immunity_period_asc'
    IS_IMMUNITY_PERIOD_DESC = 'is_immunity_period_desc'
    TOTAL_ALPHA_STAKE_ASC = 'total_alpha_stake_asc'
    TOTAL_ALPHA_STAKE_DESC = 'total_alpha_stake_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MetagraphOrder from a JSON string"""
        return cls(json.loads(json_str))


