# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.alpha_balance import AlphaBalance
from openapi_server.models.hotkey_item import HotkeyItem
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MinerColdkeyItem(BaseModel):
    """
    MinerColdkeyItem
    """ # noqa: E501
    active_subnets: int
    alpha_balances: List[AlphaBalance]
    average_mining_emission_as_tao_per_hotkey: StrictStr
    coldkey: Key
    free_balance: StrictStr
    hotkeys: List[HotkeyItem]
    total_active_hotkeys: int
    total_balance: StrictStr
    total_deregistered_hotkeys: int
    total_hotkeys_in_danger: int
    total_hotkeys_in_danger_during_period: int
    total_immune_hotkeys: int
    total_immune_hotkeys_during_period: int
    total_mining_emission_as_tao: StrictStr
    total_staked_balance_as_tao: StrictStr
    total_staked_mining_balance_as_tao: StrictStr
    total_staked_non_mining_balance_as_tao: StrictStr
    __properties: ClassVar[List[str]] = ["active_subnets", "alpha_balances", "average_mining_emission_as_tao_per_hotkey", "coldkey", "free_balance", "hotkeys", "total_active_hotkeys", "total_balance", "total_deregistered_hotkeys", "total_hotkeys_in_danger", "total_hotkeys_in_danger_during_period", "total_immune_hotkeys", "total_immune_hotkeys_during_period", "total_mining_emission_as_tao", "total_staked_balance_as_tao", "total_staked_mining_balance_as_tao", "total_staked_non_mining_balance_as_tao"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MinerColdkeyItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in alpha_balances (list)
        _items = []
        if self.alpha_balances:
            for _item in self.alpha_balances:
                if _item:
                    _items.append(_item.to_dict())
            _dict['alpha_balances'] = _items
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in hotkeys (list)
        _items = []
        if self.hotkeys:
            for _item in self.hotkeys:
                if _item:
                    _items.append(_item.to_dict())
            _dict['hotkeys'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MinerColdkeyItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_subnets": obj.get("active_subnets"),
            "alpha_balances": [AlphaBalance.from_dict(_item) for _item in obj.get("alpha_balances")] if obj.get("alpha_balances") is not None else None,
            "average_mining_emission_as_tao_per_hotkey": obj.get("average_mining_emission_as_tao_per_hotkey"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "free_balance": obj.get("free_balance"),
            "hotkeys": [HotkeyItem.from_dict(_item) for _item in obj.get("hotkeys")] if obj.get("hotkeys") is not None else None,
            "total_active_hotkeys": obj.get("total_active_hotkeys"),
            "total_balance": obj.get("total_balance"),
            "total_deregistered_hotkeys": obj.get("total_deregistered_hotkeys"),
            "total_hotkeys_in_danger": obj.get("total_hotkeys_in_danger"),
            "total_hotkeys_in_danger_during_period": obj.get("total_hotkeys_in_danger_during_period"),
            "total_immune_hotkeys": obj.get("total_immune_hotkeys"),
            "total_immune_hotkeys_during_period": obj.get("total_immune_hotkeys_during_period"),
            "total_mining_emission_as_tao": obj.get("total_mining_emission_as_tao"),
            "total_staked_balance_as_tao": obj.get("total_staked_balance_as_tao"),
            "total_staked_mining_balance_as_tao": obj.get("total_staked_mining_balance_as_tao"),
            "total_staked_non_mining_balance_as_tao": obj.get("total_staked_non_mining_balance_as_tao")
        })
        return _obj


