# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MinerWeightsItem(BaseModel):
    """
    MinerWeightsItem
    """ # noqa: E501
    block_number: int
    miner_hotkey: Key
    miner_uid: int
    netuid: int
    timestamp: datetime
    validator_hotkey: Key
    validator_uid: int
    weight: StrictStr
    __properties: ClassVar[List[str]] = ["block_number", "miner_hotkey", "miner_uid", "netuid", "timestamp", "validator_hotkey", "validator_uid", "weight"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MinerWeightsItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of miner_hotkey
        if self.miner_hotkey:
            _dict['miner_hotkey'] = self.miner_hotkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of validator_hotkey
        if self.validator_hotkey:
            _dict['validator_hotkey'] = self.validator_hotkey.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MinerWeightsItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "miner_hotkey": Key.from_dict(obj.get("miner_hotkey")) if obj.get("miner_hotkey") is not None else None,
            "miner_uid": obj.get("miner_uid"),
            "netuid": obj.get("netuid"),
            "timestamp": obj.get("timestamp"),
            "validator_hotkey": Key.from_dict(obj.get("validator_hotkey")) if obj.get("validator_hotkey") is not None else None,
            "validator_uid": obj.get("validator_uid"),
            "weight": obj.get("weight")
        })
        return _obj


