# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.miner_weights_history_order import MinerWeightsHistoryOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class MinerWeightsHistoryRequest(BaseModel):
    """
    MinerWeightsHistoryRequest
    """ # noqa: E501
    block_end: Optional[int] = Field(default=None, description="End of block range (inclusive)")
    block_number: Optional[int] = Field(default=None, description="Start of block range (inclusive)")
    block_start: Optional[int] = Field(default=None, description="Start of block range (inclusive)")
    limit: Optional[int] = None
    miner_hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    miner_uid: Optional[int] = None
    netuid: int
    order: Optional[MinerWeightsHistoryOrder] = None
    page: Optional[int] = None
    timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    validator_hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    validator_uid: Optional[int] = None
    __properties: ClassVar[List[str]] = ["block_end", "block_number", "block_start", "limit", "miner_hotkey", "miner_uid", "netuid", "order", "page", "timestamp_end", "timestamp_start", "validator_hotkey", "validator_uid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MinerWeightsHistoryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_number (nullable) is None
        # and model_fields_set contains the field
        if self.block_number is None and "block_number" in self.model_fields_set:
            _dict['block_number'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if miner_hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.miner_hotkey is None and "miner_hotkey" in self.model_fields_set:
            _dict['miner_hotkey'] = None

        # set to None if miner_uid (nullable) is None
        # and model_fields_set contains the field
        if self.miner_uid is None and "miner_uid" in self.model_fields_set:
            _dict['miner_uid'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        # set to None if validator_hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.validator_hotkey is None and "validator_hotkey" in self.model_fields_set:
            _dict['validator_hotkey'] = None

        # set to None if validator_uid (nullable) is None
        # and model_fields_set contains the field
        if self.validator_uid is None and "validator_uid" in self.model_fields_set:
            _dict['validator_uid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of MinerWeightsHistoryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_end": obj.get("block_end"),
            "block_number": obj.get("block_number"),
            "block_start": obj.get("block_start"),
            "limit": obj.get("limit"),
            "miner_hotkey": obj.get("miner_hotkey"),
            "miner_uid": obj.get("miner_uid"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start"),
            "validator_hotkey": obj.get("validator_hotkey"),
            "validator_uid": obj.get("validator_uid")
        })
        return _obj


