# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class NetworkWithAll(str, Enum):
    """
    NetworkWithAll
    """

    """
    allowed enum values
    """
    ALL = 'all'
    FINNEY = 'finney'
    NAKAMOTO = 'nakamoto'
    KUSANAGI = 'kusanagi'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkWithAll from a JSON string"""
        return cls(json.loads(json_str))


