# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.neuron_history_order import NeuronHistoryOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NeuronHistoryRequest(BaseModel):
    """
    NeuronHistoryRequest
    """ # noqa: E501
    block_end: Optional[int] = Field(default=None, description="End of block range (inclusive)")
    block_start: Optional[int] = None
    coldkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    has_dividends: Optional[StrictBool] = Field(default=None, description="Has dividends")
    has_incentive: Optional[StrictBool] = Field(default=None, description="Has incentive")
    hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    in_danger: Optional[StrictBool] = Field(default=None, description="Is in danger")
    is_immune: Optional[StrictBool] = Field(default=None, description="Start of block range (inclusive) Is immune")
    limit: Optional[int] = None
    netuid: Optional[int] = Field(default=None, description="Subnet ID")
    order: Optional[NeuronHistoryOrder] = None
    page: Optional[int] = None
    timestamp_end: Optional[int] = Field(default=None, description="End of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    timestamp_start: Optional[int] = Field(default=None, description="Start of timestamp range in Unix timestamp (seconds since 1970-01-01) (inclusive)")
    uid: Optional[int] = Field(default=None, description="Neuron ID")
    __properties: ClassVar[List[str]] = ["block_end", "block_start", "coldkey", "has_dividends", "has_incentive", "hotkey", "in_danger", "is_immune", "limit", "netuid", "order", "page", "timestamp_end", "timestamp_start", "uid"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NeuronHistoryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if coldkey (nullable) is None
        # and model_fields_set contains the field
        if self.coldkey is None and "coldkey" in self.model_fields_set:
            _dict['coldkey'] = None

        # set to None if has_dividends (nullable) is None
        # and model_fields_set contains the field
        if self.has_dividends is None and "has_dividends" in self.model_fields_set:
            _dict['has_dividends'] = None

        # set to None if has_incentive (nullable) is None
        # and model_fields_set contains the field
        if self.has_incentive is None and "has_incentive" in self.model_fields_set:
            _dict['has_incentive'] = None

        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        # set to None if in_danger (nullable) is None
        # and model_fields_set contains the field
        if self.in_danger is None and "in_danger" in self.model_fields_set:
            _dict['in_danger'] = None

        # set to None if is_immune (nullable) is None
        # and model_fields_set contains the field
        if self.is_immune is None and "is_immune" in self.model_fields_set:
            _dict['is_immune'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        # set to None if uid (nullable) is None
        # and model_fields_set contains the field
        if self.uid is None and "uid" in self.model_fields_set:
            _dict['uid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NeuronHistoryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_end": obj.get("block_end"),
            "block_start": obj.get("block_start"),
            "coldkey": obj.get("coldkey"),
            "has_dividends": obj.get("has_dividends"),
            "has_incentive": obj.get("has_incentive"),
            "hotkey": obj.get("hotkey"),
            "in_danger": obj.get("in_danger"),
            "is_immune": obj.get("is_immune"),
            "limit": obj.get("limit"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start"),
            "uid": obj.get("uid")
        })
        return _obj


