# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NeuronAggregatedItem(BaseModel):
    """
    NeuronAggregatedItem
    """ # noqa: E501
    block_number: int
    immune_count: int
    last_dereg_incentive: StrictStr
    last_dereg_pruning_score: StrictStr
    max_danger_incentive: StrictStr
    max_danger_pruning_score: StrictStr
    max_immune_incentive: StrictStr
    max_immune_pruning_score: StrictStr
    max_incentive: StrictStr
    max_mining_pruning_score: StrictStr
    max_pruning_score: StrictStr
    min_non_immune_incentive: StrictStr
    min_non_immune_pruning_score: StrictStr
    netuid: int
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["block_number", "immune_count", "last_dereg_incentive", "last_dereg_pruning_score", "max_danger_incentive", "max_danger_pruning_score", "max_immune_incentive", "max_immune_pruning_score", "max_incentive", "max_mining_pruning_score", "max_pruning_score", "min_non_immune_incentive", "min_non_immune_pruning_score", "netuid", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NeuronAggregatedItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NeuronAggregatedItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "immune_count": obj.get("immune_count"),
            "last_dereg_incentive": obj.get("last_dereg_incentive"),
            "last_dereg_pruning_score": obj.get("last_dereg_pruning_score"),
            "max_danger_incentive": obj.get("max_danger_incentive"),
            "max_danger_pruning_score": obj.get("max_danger_pruning_score"),
            "max_immune_incentive": obj.get("max_immune_incentive"),
            "max_immune_pruning_score": obj.get("max_immune_pruning_score"),
            "max_incentive": obj.get("max_incentive"),
            "max_mining_pruning_score": obj.get("max_mining_pruning_score"),
            "max_pruning_score": obj.get("max_pruning_score"),
            "min_non_immune_incentive": obj.get("min_non_immune_incentive"),
            "min_non_immune_pruning_score": obj.get("min_non_immune_pruning_score"),
            "netuid": obj.get("netuid"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


