# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class NeuronItem(BaseModel):
    """
    NeuronItem
    """ # noqa: E501
    active: StrictBool
    axon: Optional[StrictStr] = None
    block_number: int
    coldkey: Key
    consensus: StrictStr
    dividends: StrictStr
    emission: StrictStr
    hotkey: Key
    in_danger: StrictBool
    incentive: StrictStr
    is_immune: StrictBool
    mech_incentive: List[StrictStr]
    miner_rank: Optional[int] = None
    netuid: int
    pruning_score: StrictStr
    registration_block: int
    stake_weight: Optional[StrictStr] = None
    timestamp: datetime
    trust: StrictStr
    uid: int
    validator_permit: StrictBool
    validator_rank: Optional[int] = None
    validator_trust: StrictStr
    __properties: ClassVar[List[str]] = ["active", "axon", "block_number", "coldkey", "consensus", "dividends", "emission", "hotkey", "in_danger", "incentive", "is_immune", "mech_incentive", "miner_rank", "netuid", "pruning_score", "registration_block", "stake_weight", "timestamp", "trust", "uid", "validator_permit", "validator_rank", "validator_trust"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NeuronItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if axon (nullable) is None
        # and model_fields_set contains the field
        if self.axon is None and "axon" in self.model_fields_set:
            _dict['axon'] = None

        # set to None if miner_rank (nullable) is None
        # and model_fields_set contains the field
        if self.miner_rank is None and "miner_rank" in self.model_fields_set:
            _dict['miner_rank'] = None

        # set to None if stake_weight (nullable) is None
        # and model_fields_set contains the field
        if self.stake_weight is None and "stake_weight" in self.model_fields_set:
            _dict['stake_weight'] = None

        # set to None if validator_rank (nullable) is None
        # and model_fields_set contains the field
        if self.validator_rank is None and "validator_rank" in self.model_fields_set:
            _dict['validator_rank'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of NeuronItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "axon": obj.get("axon"),
            "block_number": obj.get("block_number"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "consensus": obj.get("consensus"),
            "dividends": obj.get("dividends"),
            "emission": obj.get("emission"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "in_danger": obj.get("in_danger"),
            "incentive": obj.get("incentive"),
            "is_immune": obj.get("is_immune"),
            "mech_incentive": obj.get("mech_incentive"),
            "miner_rank": obj.get("miner_rank"),
            "netuid": obj.get("netuid"),
            "pruning_score": obj.get("pruning_score"),
            "registration_block": obj.get("registration_block"),
            "stake_weight": obj.get("stake_weight"),
            "timestamp": obj.get("timestamp"),
            "trust": obj.get("trust"),
            "uid": obj.get("uid"),
            "validator_permit": obj.get("validator_permit"),
            "validator_rank": obj.get("validator_rank"),
            "validator_trust": obj.get("validator_trust")
        })
        return _obj


