# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.listing_status import ListingStatus
from openapi_server.models.otc_listing_order import OtcListingOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OtcListingRequest(BaseModel):
    """
    OtcListingRequest
    """ # noqa: E501
    amount_max: Optional[StrictStr] = None
    amount_min: Optional[StrictStr] = None
    created_block_end: Optional[int] = None
    created_block_start: Optional[int] = None
    created_timestamp_end: Optional[int] = None
    created_timestamp_start: Optional[int] = None
    hotkey: Optional[StrictStr] = None
    limit: Optional[int] = None
    listing_id: Optional[StrictStr] = None
    netuid: Optional[int] = None
    order: Optional[OtcListingOrder] = None
    page: Optional[int] = None
    price_max: Optional[StrictStr] = None
    price_min: Optional[StrictStr] = None
    seller: Optional[StrictStr] = None
    status: Optional[ListingStatus] = None
    __properties: ClassVar[List[str]] = ["amount_max", "amount_min", "created_block_end", "created_block_start", "created_timestamp_end", "created_timestamp_start", "hotkey", "limit", "listing_id", "netuid", "order", "page", "price_max", "price_min", "seller", "status"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcListingRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if amount_max (nullable) is None
        # and model_fields_set contains the field
        if self.amount_max is None and "amount_max" in self.model_fields_set:
            _dict['amount_max'] = None

        # set to None if amount_min (nullable) is None
        # and model_fields_set contains the field
        if self.amount_min is None and "amount_min" in self.model_fields_set:
            _dict['amount_min'] = None

        # set to None if created_block_end (nullable) is None
        # and model_fields_set contains the field
        if self.created_block_end is None and "created_block_end" in self.model_fields_set:
            _dict['created_block_end'] = None

        # set to None if created_block_start (nullable) is None
        # and model_fields_set contains the field
        if self.created_block_start is None and "created_block_start" in self.model_fields_set:
            _dict['created_block_start'] = None

        # set to None if created_timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.created_timestamp_end is None and "created_timestamp_end" in self.model_fields_set:
            _dict['created_timestamp_end'] = None

        # set to None if created_timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.created_timestamp_start is None and "created_timestamp_start" in self.model_fields_set:
            _dict['created_timestamp_start'] = None

        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        # set to None if listing_id (nullable) is None
        # and model_fields_set contains the field
        if self.listing_id is None and "listing_id" in self.model_fields_set:
            _dict['listing_id'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if price_max (nullable) is None
        # and model_fields_set contains the field
        if self.price_max is None and "price_max" in self.model_fields_set:
            _dict['price_max'] = None

        # set to None if price_min (nullable) is None
        # and model_fields_set contains the field
        if self.price_min is None and "price_min" in self.model_fields_set:
            _dict['price_min'] = None

        # set to None if seller (nullable) is None
        # and model_fields_set contains the field
        if self.seller is None and "seller" in self.model_fields_set:
            _dict['seller'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OtcListingRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount_max": obj.get("amount_max"),
            "amount_min": obj.get("amount_min"),
            "created_block_end": obj.get("created_block_end"),
            "created_block_start": obj.get("created_block_start"),
            "created_timestamp_end": obj.get("created_timestamp_end"),
            "created_timestamp_start": obj.get("created_timestamp_start"),
            "hotkey": obj.get("hotkey"),
            "limit": obj.get("limit"),
            "listing_id": obj.get("listing_id"),
            "netuid": obj.get("netuid"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "price_max": obj.get("price_max"),
            "price_min": obj.get("price_min"),
            "seller": obj.get("seller"),
            "status": obj.get("status")
        })
        return _obj


