# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.otc_trade_order import OtcTradeOrder
from openapi_server.models.trade_type import TradeType
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OtcTradeRequest(BaseModel):
    """
    OtcTradeRequest
    """ # noqa: E501
    block_end: Optional[int] = None
    block_start: Optional[int] = None
    buyer: Optional[StrictStr] = None
    limit: Optional[int] = None
    listing_id: Optional[StrictStr] = None
    netuid: Optional[int] = None
    offer_id: Optional[StrictStr] = None
    order: Optional[OtcTradeOrder] = None
    page: Optional[int] = None
    seller: Optional[StrictStr] = None
    timestamp_end: Optional[int] = None
    timestamp_start: Optional[int] = None
    trade_type: Optional[TradeType] = None
    __properties: ClassVar[List[str]] = ["block_end", "block_start", "buyer", "limit", "listing_id", "netuid", "offer_id", "order", "page", "seller", "timestamp_end", "timestamp_start", "trade_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcTradeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if block_end (nullable) is None
        # and model_fields_set contains the field
        if self.block_end is None and "block_end" in self.model_fields_set:
            _dict['block_end'] = None

        # set to None if block_start (nullable) is None
        # and model_fields_set contains the field
        if self.block_start is None and "block_start" in self.model_fields_set:
            _dict['block_start'] = None

        # set to None if buyer (nullable) is None
        # and model_fields_set contains the field
        if self.buyer is None and "buyer" in self.model_fields_set:
            _dict['buyer'] = None

        # set to None if listing_id (nullable) is None
        # and model_fields_set contains the field
        if self.listing_id is None and "listing_id" in self.model_fields_set:
            _dict['listing_id'] = None

        # set to None if netuid (nullable) is None
        # and model_fields_set contains the field
        if self.netuid is None and "netuid" in self.model_fields_set:
            _dict['netuid'] = None

        # set to None if offer_id (nullable) is None
        # and model_fields_set contains the field
        if self.offer_id is None and "offer_id" in self.model_fields_set:
            _dict['offer_id'] = None

        # set to None if seller (nullable) is None
        # and model_fields_set contains the field
        if self.seller is None and "seller" in self.model_fields_set:
            _dict['seller'] = None

        # set to None if timestamp_end (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_end is None and "timestamp_end" in self.model_fields_set:
            _dict['timestamp_end'] = None

        # set to None if timestamp_start (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_start is None and "timestamp_start" in self.model_fields_set:
            _dict['timestamp_start'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OtcTradeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_end": obj.get("block_end"),
            "block_start": obj.get("block_start"),
            "buyer": obj.get("buyer"),
            "limit": obj.get("limit"),
            "listing_id": obj.get("listing_id"),
            "netuid": obj.get("netuid"),
            "offer_id": obj.get("offer_id"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "seller": obj.get("seller"),
            "timestamp_end": obj.get("timestamp_end"),
            "timestamp_start": obj.get("timestamp_start"),
            "trade_type": obj.get("trade_type")
        })
        return _obj


