# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OtcOfferItem(BaseModel):
    """
    OtcOfferItem
    """ # noqa: E501
    amount: StrictStr
    buyer: Key
    created_block: int
    created_timestamp: datetime
    netuid: int
    offer_id: StrictStr
    price: StrictStr
    status: StrictStr
    updated_block: int
    updated_timestamp: datetime
    __properties: ClassVar[List[str]] = ["amount", "buyer", "created_block", "created_timestamp", "netuid", "offer_id", "price", "status", "updated_block", "updated_timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcOfferItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of buyer
        if self.buyer:
            _dict['buyer'] = self.buyer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OtcOfferItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amount": obj.get("amount"),
            "buyer": Key.from_dict(obj.get("buyer")) if obj.get("buyer") is not None else None,
            "created_block": obj.get("created_block"),
            "created_timestamp": obj.get("created_timestamp"),
            "netuid": obj.get("netuid"),
            "offer_id": obj.get("offer_id"),
            "price": obj.get("price"),
            "status": obj.get("status"),
            "updated_block": obj.get("updated_block"),
            "updated_timestamp": obj.get("updated_timestamp")
        })
        return _obj


