# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OtcOfferHistoryItem(BaseModel):
    """
    OtcOfferHistoryItem
    """ # noqa: E501
    alpha_amount: Optional[StrictStr] = None
    amount: StrictStr
    amount_returned: Optional[StrictStr] = None
    block_number: int
    buyer: Key
    event_type: StrictStr
    fee: Optional[StrictStr] = None
    id: StrictStr
    netuid: int
    offer_id: StrictStr
    price: StrictStr
    seller: Optional[Key] = None
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["alpha_amount", "amount", "amount_returned", "block_number", "buyer", "event_type", "fee", "id", "netuid", "offer_id", "price", "seller", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcOfferHistoryItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of buyer
        if self.buyer:
            _dict['buyer'] = self.buyer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seller
        if self.seller:
            _dict['seller'] = self.seller.to_dict()
        # set to None if alpha_amount (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_amount is None and "alpha_amount" in self.model_fields_set:
            _dict['alpha_amount'] = None

        # set to None if amount_returned (nullable) is None
        # and model_fields_set contains the field
        if self.amount_returned is None and "amount_returned" in self.model_fields_set:
            _dict['amount_returned'] = None

        # set to None if fee (nullable) is None
        # and model_fields_set contains the field
        if self.fee is None and "fee" in self.model_fields_set:
            _dict['fee'] = None

        # set to None if seller (nullable) is None
        # and model_fields_set contains the field
        if self.seller is None and "seller" in self.model_fields_set:
            _dict['seller'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OtcOfferHistoryItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_amount": obj.get("alpha_amount"),
            "amount": obj.get("amount"),
            "amount_returned": obj.get("amount_returned"),
            "block_number": obj.get("block_number"),
            "buyer": Key.from_dict(obj.get("buyer")) if obj.get("buyer") is not None else None,
            "event_type": obj.get("event_type"),
            "fee": obj.get("fee"),
            "id": obj.get("id"),
            "netuid": obj.get("netuid"),
            "offer_id": obj.get("offer_id"),
            "price": obj.get("price"),
            "seller": Key.from_dict(obj.get("seller")) if obj.get("seller") is not None else None,
            "timestamp": obj.get("timestamp")
        })
        return _obj


