# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OtcUserStatsOrder(str, Enum):
    """
    OtcUserStatsOrder
    """

    """
    allowed enum values
    """
    LAST_ACTIVITY_ASC = 'last_activity_asc'
    LAST_ACTIVITY_DESC = 'last_activity_desc'
    VOLUME_TAO_ASC = 'volume_tao_asc'
    VOLUME_TAO_DESC = 'volume_tao_desc'
    VOLUME_ALPHA_ASC = 'volume_alpha_asc'
    VOLUME_ALPHA_DESC = 'volume_alpha_desc'
    TOTAL_TRADES_ASC = 'total_trades_asc'
    TOTAL_TRADES_DESC = 'total_trades_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcUserStatsOrder from a JSON string"""
        return cls(json.loads(json_str))


