# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class OtcTradeItem(BaseModel):
    """
    OtcTradeItem
    """ # noqa: E501
    alpha_amount: StrictStr
    block_number: int
    buyer: Key
    fee: StrictStr
    id: StrictStr
    listing_id: Optional[StrictStr] = None
    netuid: int
    offer_id: Optional[StrictStr] = None
    price: StrictStr
    seller: Key
    tao_amount: StrictStr
    timestamp: datetime
    trade_type: StrictStr
    __properties: ClassVar[List[str]] = ["alpha_amount", "block_number", "buyer", "fee", "id", "listing_id", "netuid", "offer_id", "price", "seller", "tao_amount", "timestamp", "trade_type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OtcTradeItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of buyer
        if self.buyer:
            _dict['buyer'] = self.buyer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of seller
        if self.seller:
            _dict['seller'] = self.seller.to_dict()
        # set to None if listing_id (nullable) is None
        # and model_fields_set contains the field
        if self.listing_id is None and "listing_id" in self.model_fields_set:
            _dict['listing_id'] = None

        # set to None if offer_id (nullable) is None
        # and model_fields_set contains the field
        if self.offer_id is None and "offer_id" in self.model_fields_set:
            _dict['offer_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of OtcTradeItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alpha_amount": obj.get("alpha_amount"),
            "block_number": obj.get("block_number"),
            "buyer": Key.from_dict(obj.get("buyer")) if obj.get("buyer") is not None else None,
            "fee": obj.get("fee"),
            "id": obj.get("id"),
            "listing_id": obj.get("listing_id"),
            "netuid": obj.get("netuid"),
            "offer_id": obj.get("offer_id"),
            "price": obj.get("price"),
            "seller": Key.from_dict(obj.get("seller")) if obj.get("seller") is not None else None,
            "tao_amount": obj.get("tao_amount"),
            "timestamp": obj.get("timestamp"),
            "trade_type": obj.get("trade_type")
        })
        return _obj


