# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PriceItem(BaseModel):
    """
    PriceItem
    """ # noqa: E501
    circulating_supply: StrictStr
    created_at: datetime
    fully_diluted_market_cap: StrictStr
    last_updated: datetime
    market_cap: StrictStr
    market_cap_dominance: StrictStr
    max_supply: StrictStr
    name: StrictStr
    percent_change_1h: StrictStr
    percent_change_24h: StrictStr
    percent_change_30d: StrictStr
    percent_change_60d: StrictStr
    percent_change_7d: StrictStr
    percent_change_90d: StrictStr
    price: StrictStr
    slug: StrictStr
    symbol: StrictStr
    total_supply: StrictStr
    updated_at: datetime
    volume_24h: StrictStr
    __properties: ClassVar[List[str]] = ["circulating_supply", "created_at", "fully_diluted_market_cap", "last_updated", "market_cap", "market_cap_dominance", "max_supply", "name", "percent_change_1h", "percent_change_24h", "percent_change_30d", "percent_change_60d", "percent_change_7d", "percent_change_90d", "price", "slug", "symbol", "total_supply", "updated_at", "volume_24h"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PriceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PriceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "circulating_supply": obj.get("circulating_supply"),
            "created_at": obj.get("created_at"),
            "fully_diluted_market_cap": obj.get("fully_diluted_market_cap"),
            "last_updated": obj.get("last_updated"),
            "market_cap": obj.get("market_cap"),
            "market_cap_dominance": obj.get("market_cap_dominance"),
            "max_supply": obj.get("max_supply"),
            "name": obj.get("name"),
            "percent_change_1h": obj.get("percent_change_1h"),
            "percent_change_24h": obj.get("percent_change_24h"),
            "percent_change_30d": obj.get("percent_change_30d"),
            "percent_change_60d": obj.get("percent_change_60d"),
            "percent_change_7d": obj.get("percent_change_7d"),
            "percent_change_90d": obj.get("percent_change_90d"),
            "price": obj.get("price"),
            "slug": obj.get("slug"),
            "symbol": obj.get("symbol"),
            "total_supply": obj.get("total_supply"),
            "updated_at": obj.get("updated_at"),
            "volume_24h": obj.get("volume_24h")
        })
        return _obj


