# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from openapi_server.models.sidecar_balance_lock import SidecarBalanceLock
from openapi_server.models.sidecar_block_identifiers import SidecarBlockIdentifiers
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SidecarAccountBalanceInfo(BaseModel):
    """
    SidecarAccountBalanceInfo
    """ # noqa: E501
    at: SidecarBlockIdentifiers
    fee_frozen: StrictStr = Field(alias="feeFrozen")
    free: StrictStr
    frozen: StrictStr
    locks: List[SidecarBalanceLock]
    misc_frozen: StrictStr = Field(alias="miscFrozen")
    nonce: StrictStr
    reserved: StrictStr
    token_symbol: StrictStr = Field(alias="tokenSymbol")
    __properties: ClassVar[List[str]] = ["at", "feeFrozen", "free", "frozen", "locks", "miscFrozen", "nonce", "reserved", "tokenSymbol"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SidecarAccountBalanceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of at
        if self.at:
            _dict['at'] = self.at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in locks (list)
        _items = []
        if self.locks:
            for _item in self.locks:
                if _item:
                    _items.append(_item.to_dict())
            _dict['locks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SidecarAccountBalanceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "at": SidecarBlockIdentifiers.from_dict(obj.get("at")) if obj.get("at") is not None else None,
            "feeFrozen": obj.get("feeFrozen"),
            "free": obj.get("free"),
            "frozen": obj.get("frozen"),
            "locks": [SidecarBalanceLock.from_dict(_item) for _item in obj.get("locks")] if obj.get("locks") is not None else None,
            "miscFrozen": obj.get("miscFrozen"),
            "nonce": obj.get("nonce"),
            "reserved": obj.get("reserved"),
            "tokenSymbol": obj.get("tokenSymbol")
        })
        return _obj


