# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.sidecar_block_finalize import SidecarBlockFinalize
from openapi_server.models.sidecar_block_initialize import SidecarBlockInitialize
from openapi_server.models.sidecar_digest_item import SidecarDigestItem
from openapi_server.models.sidecar_extrinsic import SidecarExtrinsic
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SidecarBlock(BaseModel):
    """
    SidecarBlock
    """ # noqa: E501
    author_id: Optional[StrictStr] = Field(default=None, alias="authorId")
    extrinsic_root: Optional[StrictStr] = Field(default=None, alias="extrinsicRoot")
    extrinsics: List[SidecarExtrinsic]
    finalized: StrictBool
    hash: StrictStr
    logs: List[SidecarDigestItem]
    number: StrictStr
    on_finalize: SidecarBlockFinalize = Field(alias="onFinalize")
    on_initialize: SidecarBlockInitialize = Field(alias="onInitialize")
    parent_hash: StrictStr = Field(alias="parentHash")
    state_root: StrictStr = Field(alias="stateRoot")
    __properties: ClassVar[List[str]] = ["authorId", "extrinsicRoot", "extrinsics", "finalized", "hash", "logs", "number", "onFinalize", "onInitialize", "parentHash", "stateRoot"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SidecarBlock from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in extrinsics (list)
        _items = []
        if self.extrinsics:
            for _item in self.extrinsics:
                if _item:
                    _items.append(_item.to_dict())
            _dict['extrinsics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in logs (list)
        _items = []
        if self.logs:
            for _item in self.logs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['logs'] = _items
        # override the default output from pydantic by calling `to_dict()` of on_finalize
        if self.on_finalize:
            _dict['onFinalize'] = self.on_finalize.to_dict()
        # override the default output from pydantic by calling `to_dict()` of on_initialize
        if self.on_initialize:
            _dict['onInitialize'] = self.on_initialize.to_dict()
        # set to None if author_id (nullable) is None
        # and model_fields_set contains the field
        if self.author_id is None and "author_id" in self.model_fields_set:
            _dict['authorId'] = None

        # set to None if extrinsic_root (nullable) is None
        # and model_fields_set contains the field
        if self.extrinsic_root is None and "extrinsic_root" in self.model_fields_set:
            _dict['extrinsicRoot'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SidecarBlock from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authorId": obj.get("authorId"),
            "extrinsicRoot": obj.get("extrinsicRoot"),
            "extrinsics": [SidecarExtrinsic.from_dict(_item) for _item in obj.get("extrinsics")] if obj.get("extrinsics") is not None else None,
            "finalized": obj.get("finalized"),
            "hash": obj.get("hash"),
            "logs": [SidecarDigestItem.from_dict(_item) for _item in obj.get("logs")] if obj.get("logs") is not None else None,
            "number": obj.get("number"),
            "onFinalize": SidecarBlockFinalize.from_dict(obj.get("onFinalize")) if obj.get("onFinalize") is not None else None,
            "onInitialize": SidecarBlockInitialize.from_dict(obj.get("onInitialize")) if obj.get("onInitialize") is not None else None,
            "parentHash": obj.get("parentHash"),
            "stateRoot": obj.get("stateRoot")
        })
        return _obj


