# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.sidecar_block_identifiers import SidecarBlockIdentifiers
from openapi_server.models.sidecar_pallet_storage_item_metadata import SidecarPalletStorageItemMetadata
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SidecarPalletStorageItem(BaseModel):
    """
    SidecarPalletStorageItem
    """ # noqa: E501
    at: SidecarBlockIdentifiers
    keys: List[StrictStr]
    metadata: Optional[SidecarPalletStorageItemMetadata] = None
    pallet: StrictStr
    pallet_index: StrictStr = Field(alias="palletIndex")
    storage_item: StrictStr = Field(alias="storageItem")
    value: Optional[Any]
    __properties: ClassVar[List[str]] = ["at", "keys", "metadata", "pallet", "palletIndex", "storageItem", "value"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SidecarPalletStorageItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of at
        if self.at:
            _dict['at'] = self.at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SidecarPalletStorageItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "at": SidecarBlockIdentifiers.from_dict(obj.get("at")) if obj.get("at") is not None else None,
            "keys": obj.get("keys"),
            "metadata": SidecarPalletStorageItemMetadata.from_dict(obj.get("metadata")) if obj.get("metadata") is not None else None,
            "pallet": obj.get("pallet"),
            "palletIndex": obj.get("palletIndex"),
            "storageItem": obj.get("storageItem"),
            "value": obj.get("value")
        })
        return _obj


