# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class StatsItem(BaseModel):
    """
    StatsItem
    """ # noqa: E501
    accounts: int
    balance_holders: int
    block_number: int
    extrinsics: int
    free: StrictStr
    issued: StrictStr
    staked: StrictStr
    staked_alpha: Optional[StrictStr] = None
    staked_root: Optional[StrictStr] = None
    staked_root_on_keep: Optional[StrictStr] = None
    staked_root_on_swap: Optional[StrictStr] = None
    subnet_locked: StrictStr
    subnet_registration_cost: StrictStr
    subnets: int
    timestamp: datetime
    transfers: int
    __properties: ClassVar[List[str]] = ["accounts", "balance_holders", "block_number", "extrinsics", "free", "issued", "staked", "staked_alpha", "staked_root", "staked_root_on_keep", "staked_root_on_swap", "subnet_locked", "subnet_registration_cost", "subnets", "timestamp", "transfers"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatsItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if staked_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.staked_alpha is None and "staked_alpha" in self.model_fields_set:
            _dict['staked_alpha'] = None

        # set to None if staked_root (nullable) is None
        # and model_fields_set contains the field
        if self.staked_root is None and "staked_root" in self.model_fields_set:
            _dict['staked_root'] = None

        # set to None if staked_root_on_keep (nullable) is None
        # and model_fields_set contains the field
        if self.staked_root_on_keep is None and "staked_root_on_keep" in self.model_fields_set:
            _dict['staked_root_on_keep'] = None

        # set to None if staked_root_on_swap (nullable) is None
        # and model_fields_set contains the field
        if self.staked_root_on_swap is None and "staked_root_on_swap" in self.model_fields_set:
            _dict['staked_root_on_swap'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of StatsItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accounts": obj.get("accounts"),
            "balance_holders": obj.get("balance_holders"),
            "block_number": obj.get("block_number"),
            "extrinsics": obj.get("extrinsics"),
            "free": obj.get("free"),
            "issued": obj.get("issued"),
            "staked": obj.get("staked"),
            "staked_alpha": obj.get("staked_alpha"),
            "staked_root": obj.get("staked_root"),
            "staked_root_on_keep": obj.get("staked_root_on_keep"),
            "staked_root_on_swap": obj.get("staked_root_on_swap"),
            "subnet_locked": obj.get("subnet_locked"),
            "subnet_registration_cost": obj.get("subnet_registration_cost"),
            "subnets": obj.get("subnets"),
            "timestamp": obj.get("timestamp"),
            "transfers": obj.get("transfers")
        })
        return _obj


