# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubnetOwnerItem(BaseModel):
    """
    SubnetOwnerItem
    """ # noqa: E501
    block_number: int
    is_coldkey_swap: StrictBool
    netuid: int
    owner: Key
    pending_owner: Optional[Key] = None
    pending_owner_block_number: Optional[int] = None
    pending_owner_timestamp: Optional[datetime] = None
    previous_owner: Optional[Key] = None
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["block_number", "is_coldkey_swap", "netuid", "owner", "pending_owner", "pending_owner_block_number", "pending_owner_timestamp", "previous_owner", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubnetOwnerItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of pending_owner
        if self.pending_owner:
            _dict['pending_owner'] = self.pending_owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of previous_owner
        if self.previous_owner:
            _dict['previous_owner'] = self.previous_owner.to_dict()
        # set to None if pending_owner (nullable) is None
        # and model_fields_set contains the field
        if self.pending_owner is None and "pending_owner" in self.model_fields_set:
            _dict['pending_owner'] = None

        # set to None if pending_owner_block_number (nullable) is None
        # and model_fields_set contains the field
        if self.pending_owner_block_number is None and "pending_owner_block_number" in self.model_fields_set:
            _dict['pending_owner_block_number'] = None

        # set to None if pending_owner_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.pending_owner_timestamp is None and "pending_owner_timestamp" in self.model_fields_set:
            _dict['pending_owner_timestamp'] = None

        # set to None if previous_owner (nullable) is None
        # and model_fields_set contains the field
        if self.previous_owner is None and "previous_owner" in self.model_fields_set:
            _dict['previous_owner'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubnetOwnerItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "is_coldkey_swap": obj.get("is_coldkey_swap"),
            "netuid": obj.get("netuid"),
            "owner": Key.from_dict(obj.get("owner")) if obj.get("owner") is not None else None,
            "pending_owner": Key.from_dict(obj.get("pending_owner")) if obj.get("pending_owner") is not None else None,
            "pending_owner_block_number": obj.get("pending_owner_block_number"),
            "pending_owner_timestamp": obj.get("pending_owner_timestamp"),
            "previous_owner": Key.from_dict(obj.get("previous_owner")) if obj.get("previous_owner") is not None else None,
            "timestamp": obj.get("timestamp")
        })
        return _obj


