# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubnetRegistrationItem(BaseModel):
    """
    SubnetRegistrationItem
    """ # noqa: E501
    block_number: int
    netuid: int
    owner: Optional[Key] = None
    recycled_at_registration: StrictStr
    registered_by: Optional[Key] = None
    registration_cost: StrictStr
    timestamp: datetime
    __properties: ClassVar[List[str]] = ["block_number", "netuid", "owner", "recycled_at_registration", "registered_by", "registration_cost", "timestamp"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubnetRegistrationItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of registered_by
        if self.registered_by:
            _dict['registered_by'] = self.registered_by.to_dict()
        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        # set to None if registered_by (nullable) is None
        # and model_fields_set contains the field
        if self.registered_by is None and "registered_by" in self.model_fields_set:
            _dict['registered_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubnetRegistrationItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "netuid": obj.get("netuid"),
            "owner": Key.from_dict(obj.get("owner")) if obj.get("owner") is not None else None,
            "recycled_at_registration": obj.get("recycled_at_registration"),
            "registered_by": Key.from_dict(obj.get("registered_by")) if obj.get("registered_by") is not None else None,
            "registration_cost": obj.get("registration_cost"),
            "timestamp": obj.get("timestamp")
        })
        return _obj


