# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubnetIdentityItem(BaseModel):
    """
    SubnetIdentityItem
    """ # noqa: E501
    additional: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    discord: Optional[StrictStr] = None
    github_repo: Optional[StrictStr] = None
    logo_url: Optional[StrictStr] = None
    netuid: int
    subnet_contact: Optional[StrictStr] = None
    subnet_name: StrictStr
    subnet_url: Optional[StrictStr] = None
    summary: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    twitter: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["additional", "description", "discord", "github_repo", "logo_url", "netuid", "subnet_contact", "subnet_name", "subnet_url", "summary", "tags", "twitter"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubnetIdentityItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if additional (nullable) is None
        # and model_fields_set contains the field
        if self.additional is None and "additional" in self.model_fields_set:
            _dict['additional'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if discord (nullable) is None
        # and model_fields_set contains the field
        if self.discord is None and "discord" in self.model_fields_set:
            _dict['discord'] = None

        # set to None if github_repo (nullable) is None
        # and model_fields_set contains the field
        if self.github_repo is None and "github_repo" in self.model_fields_set:
            _dict['github_repo'] = None

        # set to None if logo_url (nullable) is None
        # and model_fields_set contains the field
        if self.logo_url is None and "logo_url" in self.model_fields_set:
            _dict['logo_url'] = None

        # set to None if subnet_contact (nullable) is None
        # and model_fields_set contains the field
        if self.subnet_contact is None and "subnet_contact" in self.model_fields_set:
            _dict['subnet_contact'] = None

        # set to None if subnet_url (nullable) is None
        # and model_fields_set contains the field
        if self.subnet_url is None and "subnet_url" in self.model_fields_set:
            _dict['subnet_url'] = None

        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['summary'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if twitter (nullable) is None
        # and model_fields_set contains the field
        if self.twitter is None and "twitter" in self.model_fields_set:
            _dict['twitter'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubnetIdentityItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additional": obj.get("additional"),
            "description": obj.get("description"),
            "discord": obj.get("discord"),
            "github_repo": obj.get("github_repo"),
            "logo_url": obj.get("logo_url"),
            "netuid": obj.get("netuid"),
            "subnet_contact": obj.get("subnet_contact"),
            "subnet_name": obj.get("subnet_name"),
            "subnet_url": obj.get("subnet_url"),
            "summary": obj.get("summary"),
            "tags": obj.get("tags"),
            "twitter": obj.get("twitter")
        })
        return _obj


