# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SubnetItem(BaseModel):
    """
    SubnetItem
    """ # noqa: E501
    active_dual: int
    active_keys: int
    active_miners: int
    active_validators: int
    activity_cutoff: int
    adjustment_alpha: Optional[StrictStr] = None
    adjustment_interval: int
    alpha_high: Optional[StrictStr] = None
    alpha_low: Optional[StrictStr] = None
    alpha_sigmoid_steepness: Optional[int] = None
    block_number: int
    blocks_since_last_step: int
    blocks_until_next_adjustment: int
    blocks_until_next_epoch: int
    bonds_moving_avg: StrictStr
    bonds_penalty: Optional[StrictStr] = None
    bonds_reset_on: Optional[StrictBool] = None
    commit_reveal_weights_enabled: StrictBool
    commit_reveal_weights_interval: Optional[int] = None
    difficulty: StrictStr
    ema_price_halving_blocks: Optional[int] = None
    ema_tao_flow: StrictStr
    emission: StrictStr
    enabled_user_liquidity: Optional[StrictBool] = None
    excess_tao: Optional[StrictStr] = None
    fee_rate: Optional[StrictStr] = None
    immune_owner_uids_limit: int
    immunity_period: int
    kappa: int
    last_adjustment_block: Optional[int] = None
    liquid_alpha_enabled: Optional[StrictBool] = None
    max_burn: StrictStr
    max_difficulty: StrictStr
    max_neurons: int
    max_regs_per_block: int
    max_validators: int
    max_weights_limit: int
    mech_count: int
    mech_emission_split: List[StrictStr]
    min_allowed_weights: int
    min_burn: StrictStr
    min_difficulty: StrictStr
    modality: int
    netuid: int
    neuron_registration_cost: StrictStr
    neuron_registrations_this_interval: int
    owner: Optional[Key] = None
    owner_hotkey: Optional[Key] = None
    pow_registration_allowed: StrictBool
    projected_emission: StrictStr
    recycled_24_hours: StrictStr
    recycled_lifetime: StrictStr
    recycled_since_registration: StrictStr
    registration_allowed: StrictBool
    registration_block_number: Optional[int] = None
    registration_cost: Optional[StrictStr] = None
    registration_timestamp: Optional[datetime] = None
    reveal_period_epochs: Optional[int] = None
    rho: int
    serving_rate_limit: StrictStr
    subtoken_enabled: Optional[StrictBool] = None
    swap_v3_initialized: Optional[StrictBool] = None
    tao_flow: Optional[StrictStr] = None
    target_regs_per_interval: int
    tempo: int
    timestamp: datetime
    transfer_toggle: Optional[StrictBool] = None
    validators: int
    weights_rate_limit: StrictStr
    weights_version: StrictStr
    yuma3_on: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["active_dual", "active_keys", "active_miners", "active_validators", "activity_cutoff", "adjustment_alpha", "adjustment_interval", "alpha_high", "alpha_low", "alpha_sigmoid_steepness", "block_number", "blocks_since_last_step", "blocks_until_next_adjustment", "blocks_until_next_epoch", "bonds_moving_avg", "bonds_penalty", "bonds_reset_on", "commit_reveal_weights_enabled", "commit_reveal_weights_interval", "difficulty", "ema_price_halving_blocks", "ema_tao_flow", "emission", "enabled_user_liquidity", "excess_tao", "fee_rate", "immune_owner_uids_limit", "immunity_period", "kappa", "last_adjustment_block", "liquid_alpha_enabled", "max_burn", "max_difficulty", "max_neurons", "max_regs_per_block", "max_validators", "max_weights_limit", "mech_count", "mech_emission_split", "min_allowed_weights", "min_burn", "min_difficulty", "modality", "netuid", "neuron_registration_cost", "neuron_registrations_this_interval", "owner", "owner_hotkey", "pow_registration_allowed", "projected_emission", "recycled_24_hours", "recycled_lifetime", "recycled_since_registration", "registration_allowed", "registration_block_number", "registration_cost", "registration_timestamp", "reveal_period_epochs", "rho", "serving_rate_limit", "subtoken_enabled", "swap_v3_initialized", "tao_flow", "target_regs_per_interval", "tempo", "timestamp", "transfer_toggle", "validators", "weights_rate_limit", "weights_version", "yuma3_on"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubnetItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner_hotkey
        if self.owner_hotkey:
            _dict['owner_hotkey'] = self.owner_hotkey.to_dict()
        # set to None if adjustment_alpha (nullable) is None
        # and model_fields_set contains the field
        if self.adjustment_alpha is None and "adjustment_alpha" in self.model_fields_set:
            _dict['adjustment_alpha'] = None

        # set to None if alpha_high (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_high is None and "alpha_high" in self.model_fields_set:
            _dict['alpha_high'] = None

        # set to None if alpha_low (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_low is None and "alpha_low" in self.model_fields_set:
            _dict['alpha_low'] = None

        # set to None if alpha_sigmoid_steepness (nullable) is None
        # and model_fields_set contains the field
        if self.alpha_sigmoid_steepness is None and "alpha_sigmoid_steepness" in self.model_fields_set:
            _dict['alpha_sigmoid_steepness'] = None

        # set to None if bonds_penalty (nullable) is None
        # and model_fields_set contains the field
        if self.bonds_penalty is None and "bonds_penalty" in self.model_fields_set:
            _dict['bonds_penalty'] = None

        # set to None if bonds_reset_on (nullable) is None
        # and model_fields_set contains the field
        if self.bonds_reset_on is None and "bonds_reset_on" in self.model_fields_set:
            _dict['bonds_reset_on'] = None

        # set to None if commit_reveal_weights_interval (nullable) is None
        # and model_fields_set contains the field
        if self.commit_reveal_weights_interval is None and "commit_reveal_weights_interval" in self.model_fields_set:
            _dict['commit_reveal_weights_interval'] = None

        # set to None if ema_price_halving_blocks (nullable) is None
        # and model_fields_set contains the field
        if self.ema_price_halving_blocks is None and "ema_price_halving_blocks" in self.model_fields_set:
            _dict['ema_price_halving_blocks'] = None

        # set to None if enabled_user_liquidity (nullable) is None
        # and model_fields_set contains the field
        if self.enabled_user_liquidity is None and "enabled_user_liquidity" in self.model_fields_set:
            _dict['enabled_user_liquidity'] = None

        # set to None if excess_tao (nullable) is None
        # and model_fields_set contains the field
        if self.excess_tao is None and "excess_tao" in self.model_fields_set:
            _dict['excess_tao'] = None

        # set to None if fee_rate (nullable) is None
        # and model_fields_set contains the field
        if self.fee_rate is None and "fee_rate" in self.model_fields_set:
            _dict['fee_rate'] = None

        # set to None if last_adjustment_block (nullable) is None
        # and model_fields_set contains the field
        if self.last_adjustment_block is None and "last_adjustment_block" in self.model_fields_set:
            _dict['last_adjustment_block'] = None

        # set to None if liquid_alpha_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.liquid_alpha_enabled is None and "liquid_alpha_enabled" in self.model_fields_set:
            _dict['liquid_alpha_enabled'] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        # set to None if owner_hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.owner_hotkey is None and "owner_hotkey" in self.model_fields_set:
            _dict['owner_hotkey'] = None

        # set to None if registration_block_number (nullable) is None
        # and model_fields_set contains the field
        if self.registration_block_number is None and "registration_block_number" in self.model_fields_set:
            _dict['registration_block_number'] = None

        # set to None if registration_cost (nullable) is None
        # and model_fields_set contains the field
        if self.registration_cost is None and "registration_cost" in self.model_fields_set:
            _dict['registration_cost'] = None

        # set to None if registration_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.registration_timestamp is None and "registration_timestamp" in self.model_fields_set:
            _dict['registration_timestamp'] = None

        # set to None if reveal_period_epochs (nullable) is None
        # and model_fields_set contains the field
        if self.reveal_period_epochs is None and "reveal_period_epochs" in self.model_fields_set:
            _dict['reveal_period_epochs'] = None

        # set to None if subtoken_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.subtoken_enabled is None and "subtoken_enabled" in self.model_fields_set:
            _dict['subtoken_enabled'] = None

        # set to None if swap_v3_initialized (nullable) is None
        # and model_fields_set contains the field
        if self.swap_v3_initialized is None and "swap_v3_initialized" in self.model_fields_set:
            _dict['swap_v3_initialized'] = None

        # set to None if tao_flow (nullable) is None
        # and model_fields_set contains the field
        if self.tao_flow is None and "tao_flow" in self.model_fields_set:
            _dict['tao_flow'] = None

        # set to None if transfer_toggle (nullable) is None
        # and model_fields_set contains the field
        if self.transfer_toggle is None and "transfer_toggle" in self.model_fields_set:
            _dict['transfer_toggle'] = None

        # set to None if yuma3_on (nullable) is None
        # and model_fields_set contains the field
        if self.yuma3_on is None and "yuma3_on" in self.model_fields_set:
            _dict['yuma3_on'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SubnetItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_dual": obj.get("active_dual"),
            "active_keys": obj.get("active_keys"),
            "active_miners": obj.get("active_miners"),
            "active_validators": obj.get("active_validators"),
            "activity_cutoff": obj.get("activity_cutoff"),
            "adjustment_alpha": obj.get("adjustment_alpha"),
            "adjustment_interval": obj.get("adjustment_interval"),
            "alpha_high": obj.get("alpha_high"),
            "alpha_low": obj.get("alpha_low"),
            "alpha_sigmoid_steepness": obj.get("alpha_sigmoid_steepness"),
            "block_number": obj.get("block_number"),
            "blocks_since_last_step": obj.get("blocks_since_last_step"),
            "blocks_until_next_adjustment": obj.get("blocks_until_next_adjustment"),
            "blocks_until_next_epoch": obj.get("blocks_until_next_epoch"),
            "bonds_moving_avg": obj.get("bonds_moving_avg"),
            "bonds_penalty": obj.get("bonds_penalty"),
            "bonds_reset_on": obj.get("bonds_reset_on"),
            "commit_reveal_weights_enabled": obj.get("commit_reveal_weights_enabled"),
            "commit_reveal_weights_interval": obj.get("commit_reveal_weights_interval"),
            "difficulty": obj.get("difficulty"),
            "ema_price_halving_blocks": obj.get("ema_price_halving_blocks"),
            "ema_tao_flow": obj.get("ema_tao_flow"),
            "emission": obj.get("emission"),
            "enabled_user_liquidity": obj.get("enabled_user_liquidity"),
            "excess_tao": obj.get("excess_tao"),
            "fee_rate": obj.get("fee_rate"),
            "immune_owner_uids_limit": obj.get("immune_owner_uids_limit"),
            "immunity_period": obj.get("immunity_period"),
            "kappa": obj.get("kappa"),
            "last_adjustment_block": obj.get("last_adjustment_block"),
            "liquid_alpha_enabled": obj.get("liquid_alpha_enabled"),
            "max_burn": obj.get("max_burn"),
            "max_difficulty": obj.get("max_difficulty"),
            "max_neurons": obj.get("max_neurons"),
            "max_regs_per_block": obj.get("max_regs_per_block"),
            "max_validators": obj.get("max_validators"),
            "max_weights_limit": obj.get("max_weights_limit"),
            "mech_count": obj.get("mech_count"),
            "mech_emission_split": obj.get("mech_emission_split"),
            "min_allowed_weights": obj.get("min_allowed_weights"),
            "min_burn": obj.get("min_burn"),
            "min_difficulty": obj.get("min_difficulty"),
            "modality": obj.get("modality"),
            "netuid": obj.get("netuid"),
            "neuron_registration_cost": obj.get("neuron_registration_cost"),
            "neuron_registrations_this_interval": obj.get("neuron_registrations_this_interval"),
            "owner": Key.from_dict(obj.get("owner")) if obj.get("owner") is not None else None,
            "owner_hotkey": Key.from_dict(obj.get("owner_hotkey")) if obj.get("owner_hotkey") is not None else None,
            "pow_registration_allowed": obj.get("pow_registration_allowed"),
            "projected_emission": obj.get("projected_emission"),
            "recycled_24_hours": obj.get("recycled_24_hours"),
            "recycled_lifetime": obj.get("recycled_lifetime"),
            "recycled_since_registration": obj.get("recycled_since_registration"),
            "registration_allowed": obj.get("registration_allowed"),
            "registration_block_number": obj.get("registration_block_number"),
            "registration_cost": obj.get("registration_cost"),
            "registration_timestamp": obj.get("registration_timestamp"),
            "reveal_period_epochs": obj.get("reveal_period_epochs"),
            "rho": obj.get("rho"),
            "serving_rate_limit": obj.get("serving_rate_limit"),
            "subtoken_enabled": obj.get("subtoken_enabled"),
            "swap_v3_initialized": obj.get("swap_v3_initialized"),
            "tao_flow": obj.get("tao_flow"),
            "target_regs_per_interval": obj.get("target_regs_per_interval"),
            "tempo": obj.get("tempo"),
            "timestamp": obj.get("timestamp"),
            "transfer_toggle": obj.get("transfer_toggle"),
            "validators": obj.get("validators"),
            "weights_rate_limit": obj.get("weights_rate_limit"),
            "weights_version": obj.get("weights_version"),
            "yuma3_on": obj.get("yuma3_on")
        })
        return _obj


