# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class SymbolInfoResponse(BaseModel):
    """
    SymbolInfoResponse
    """ # noqa: E501
    description: List[StrictStr]
    exchange_listed: StrictStr = Field(alias="exchange-listed")
    exchange_traded: StrictStr = Field(alias="exchange-traded")
    has_dwm: StrictBool = Field(alias="has-dwm")
    has_intraday: StrictBool = Field(alias="has-intraday")
    minmovement: Annotated[int, Field(strict=True, ge=0)]
    pricescale: Annotated[int, Field(strict=True, ge=0)]
    session: StrictStr
    session_regular: StrictStr = Field(alias="session-regular")
    symbol: List[StrictStr]
    timezone: StrictStr
    type: List[StrictStr]
    __properties: ClassVar[List[str]] = ["description", "exchange-listed", "exchange-traded", "has-dwm", "has-intraday", "minmovement", "pricescale", "session", "session-regular", "symbol", "timezone", "type"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SymbolInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of SymbolInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "exchange-listed": obj.get("exchange-listed"),
            "exchange-traded": obj.get("exchange-traded"),
            "has-dwm": obj.get("has-dwm"),
            "has-intraday": obj.get("has-intraday"),
            "minmovement": obj.get("minmovement"),
            "pricescale": obj.get("pricescale"),
            "session": obj.get("session"),
            "session-regular": obj.get("session-regular"),
            "symbol": obj.get("symbol"),
            "timezone": obj.get("timezone"),
            "type": obj.get("type")
        })
        return _obj


