# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.validator_order import ValidatorOrder
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ValidatorRequest(BaseModel):
    """
    ValidatorRequest
    """ # noqa: E501
    apr_max: Optional[StrictStr] = None
    apr_min: Optional[StrictStr] = None
    hotkey: Optional[StrictStr] = Field(default=None, description="SS58 or hex format")
    limit: Optional[int] = None
    order: Optional[ValidatorOrder] = None
    page: Optional[int] = None
    stake_max: Optional[StrictStr] = None
    stake_min: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["apr_max", "apr_min", "hotkey", "limit", "order", "page", "stake_max", "stake_min"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # set to None if apr_max (nullable) is None
        # and model_fields_set contains the field
        if self.apr_max is None and "apr_max" in self.model_fields_set:
            _dict['apr_max'] = None

        # set to None if apr_min (nullable) is None
        # and model_fields_set contains the field
        if self.apr_min is None and "apr_min" in self.model_fields_set:
            _dict['apr_min'] = None

        # set to None if hotkey (nullable) is None
        # and model_fields_set contains the field
        if self.hotkey is None and "hotkey" in self.model_fields_set:
            _dict['hotkey'] = None

        # set to None if stake_max (nullable) is None
        # and model_fields_set contains the field
        if self.stake_max is None and "stake_max" in self.model_fields_set:
            _dict['stake_max'] = None

        # set to None if stake_min (nullable) is None
        # and model_fields_set contains the field
        if self.stake_min is None and "stake_min" in self.model_fields_set:
            _dict['stake_min'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ValidatorRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apr_max": obj.get("apr_max"),
            "apr_min": obj.get("apr_min"),
            "hotkey": obj.get("hotkey"),
            "limit": obj.get("limit"),
            "order": obj.get("order"),
            "page": obj.get("page"),
            "stake_max": obj.get("stake_max"),
            "stake_min": obj.get("stake_min")
        })
        return _obj


