# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
from openapi_server.models.weight_v2 import WeightV2
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ValidatorWeightsV2Item(BaseModel):
    """
    ValidatorWeightsV2Item
    """ # noqa: E501
    block_number: int
    hotkey: Key
    netuid: int
    timestamp: datetime
    uid: Optional[int] = None
    weights: List[WeightV2]
    __properties: ClassVar[List[str]] = ["block_number", "hotkey", "netuid", "timestamp", "uid", "weights"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorWeightsV2Item from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in weights (list)
        _items = []
        if self.weights:
            for _item in self.weights:
                if _item:
                    _items.append(_item.to_dict())
            _dict['weights'] = _items
        # set to None if uid (nullable) is None
        # and model_fields_set contains the field
        if self.uid is None and "uid" in self.model_fields_set:
            _dict['uid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ValidatorWeightsV2Item from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_number": obj.get("block_number"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "netuid": obj.get("netuid"),
            "timestamp": obj.get("timestamp"),
            "uid": obj.get("uid"),
            "weights": [WeightV2.from_dict(_item) for _item in obj.get("weights")] if obj.get("weights") is not None else None
        })
        return _obj


