# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ValidatorOrder(str, Enum):
    """
    ValidatorOrder
    """

    """
    allowed enum values
    """
    RANK_ASC = 'rank_asc'
    RANK_DESC = 'rank_desc'
    DOMINANCE_ASC = 'dominance_asc'
    DOMINANCE_DESC = 'dominance_desc'
    STAKE_ASC = 'stake_asc'
    STAKE_DESC = 'stake_desc'
    STAKE_CHANGE_ASC = 'stake_change_asc'
    STAKE_CHANGE_DESC = 'stake_change_desc'
    NOMINATORS_ASC = 'nominators_asc'
    NOMINATORS_DESC = 'nominators_desc'
    NOMINATORS_CHANGE_ASC = 'nominators_change_asc'
    NOMINATORS_CHANGE_DESC = 'nominators_change_desc'
    TAKE_ASC = 'take_asc'
    TAKE_DESC = 'take_desc'
    NOMINATOR_RETURN_ASC = 'nominator_return_asc'
    NOMINATOR_RETURN_DESC = 'nominator_return_desc'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorOrder from a JSON string"""
        return cls(json.loads(json_str))


