# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ValidatorWeightsCall(str, Enum):
    """
    ValidatorWeightsCall
    """

    """
    allowed enum values
    """
    SET_WEIGHTS = 'set_weights'
    SET_MECHANISM_WEIGHTS = 'set_mechanism_weights'
    REVEAL_WEIGHTS = 'reveal_weights'
    REVEAL_MECHANISM_WEIGHTS = 'reveal_mechanism_weights'
    COMMIT_WEIGHTS = 'commit_weights'
    COMMIT_MECHANISM_WEIGHTS = 'commit_mechanism_weights'
    COMMIT_CRV3_WEIGHTS = 'commit_crv3_weights'
    COMMIT_CRV3_MECHANISM_WEIGHTS = 'commit_crv3_mechanism_weights'
    REVEAL_CRV3_WEIGHTS = 'reveal_crv3_weights'
    COMMIT_TIMELOCKED_WEIGHTS = 'commit_timelocked_weights'
    COMMIT_TIMELOCKED_MECHANISM_WEIGHTS = 'commit_timelocked_mechanism_weights'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorWeightsCall from a JSON string"""
        return cls(json.loads(json_str))


