# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ValidatorMetricsItem(BaseModel):
    """
    ValidatorMetricsItem
    """ # noqa: E501
    active: StrictBool
    axon_info: Optional[Any] = None
    block_number: int
    coldkey: Key
    consensus: StrictStr
    daily_reward: StrictStr
    dividends: StrictStr
    emission: StrictStr
    hotkey: Key
    incentive: StrictStr
    is_immunity_period: StrictBool
    netuid: int
    rank: int
    registered_block_number: int
    stake: StrictStr
    timestamp: datetime
    trust: StrictStr
    uid: int
    updated: int
    validator_permit: StrictBool
    validator_trust: StrictStr
    __properties: ClassVar[List[str]] = ["active", "axon_info", "block_number", "coldkey", "consensus", "daily_reward", "dividends", "emission", "hotkey", "incentive", "is_immunity_period", "netuid", "rank", "registered_block_number", "stake", "timestamp", "trust", "uid", "updated", "validator_permit", "validator_trust"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorMetricsItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # set to None if axon_info (nullable) is None
        # and model_fields_set contains the field
        if self.axon_info is None and "axon_info" in self.model_fields_set:
            _dict['axon_info'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ValidatorMetricsItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "axon_info": obj.get("axon_info"),
            "block_number": obj.get("block_number"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "consensus": obj.get("consensus"),
            "daily_reward": obj.get("daily_reward"),
            "dividends": obj.get("dividends"),
            "emission": obj.get("emission"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "incentive": obj.get("incentive"),
            "is_immunity_period": obj.get("is_immunity_period"),
            "netuid": obj.get("netuid"),
            "rank": obj.get("rank"),
            "registered_block_number": obj.get("registered_block_number"),
            "stake": obj.get("stake"),
            "timestamp": obj.get("timestamp"),
            "trust": obj.get("trust"),
            "uid": obj.get("uid"),
            "updated": obj.get("updated"),
            "validator_permit": obj.get("validator_permit"),
            "validator_trust": obj.get("validator_trust")
        })
        return _obj


