# coding: utf-8

"""
    taostats

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.8.51
    Contact: dev@taostats.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json




from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_server.models.key import Key
from openapi_server.models.subnet_dominance import SubnetDominance
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ValidatorItem(BaseModel):
    """
    ValidatorItem
    """ # noqa: E501
    apr: StrictStr
    apr_30_day_average: StrictStr
    apr_7_day_average: StrictStr
    block_number: int
    blocks_until_next_reward: Optional[int] = None
    coldkey: Key
    created_on_date: date
    dominance: StrictStr
    hotkey: Key
    last_reward_block: Optional[int] = None
    name: Optional[StrictStr] = None
    nominator_return_per_k: StrictStr
    nominator_return_per_k_30_day_average: StrictStr
    nominator_return_per_k_7_day_average: StrictStr
    nominators: int
    nominators_24_hr_change: int
    pending_emission: Optional[StrictStr] = None
    permits: List[int]
    rank: int
    registrations: List[int]
    stake: StrictStr
    stake_24_hr_change: StrictStr
    subnet_dominance: List[SubnetDominance]
    system_stake: StrictStr
    take: StrictStr
    timestamp: datetime
    total_daily_return: StrictStr
    validator_return: StrictStr
    validator_stake: StrictStr
    __properties: ClassVar[List[str]] = ["apr", "apr_30_day_average", "apr_7_day_average", "block_number", "blocks_until_next_reward", "coldkey", "created_on_date", "dominance", "hotkey", "last_reward_block", "name", "nominator_return_per_k", "nominator_return_per_k_30_day_average", "nominator_return_per_k_7_day_average", "nominators", "nominators_24_hr_change", "pending_emission", "permits", "rank", "registrations", "stake", "stake_24_hr_change", "subnet_dominance", "system_stake", "take", "timestamp", "total_daily_return", "validator_return", "validator_stake"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ValidatorItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of coldkey
        if self.coldkey:
            _dict['coldkey'] = self.coldkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hotkey
        if self.hotkey:
            _dict['hotkey'] = self.hotkey.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in subnet_dominance (list)
        _items = []
        if self.subnet_dominance:
            for _item in self.subnet_dominance:
                if _item:
                    _items.append(_item.to_dict())
            _dict['subnet_dominance'] = _items
        # set to None if blocks_until_next_reward (nullable) is None
        # and model_fields_set contains the field
        if self.blocks_until_next_reward is None and "blocks_until_next_reward" in self.model_fields_set:
            _dict['blocks_until_next_reward'] = None

        # set to None if last_reward_block (nullable) is None
        # and model_fields_set contains the field
        if self.last_reward_block is None and "last_reward_block" in self.model_fields_set:
            _dict['last_reward_block'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if pending_emission (nullable) is None
        # and model_fields_set contains the field
        if self.pending_emission is None and "pending_emission" in self.model_fields_set:
            _dict['pending_emission'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ValidatorItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apr": obj.get("apr"),
            "apr_30_day_average": obj.get("apr_30_day_average"),
            "apr_7_day_average": obj.get("apr_7_day_average"),
            "block_number": obj.get("block_number"),
            "blocks_until_next_reward": obj.get("blocks_until_next_reward"),
            "coldkey": Key.from_dict(obj.get("coldkey")) if obj.get("coldkey") is not None else None,
            "created_on_date": obj.get("created_on_date"),
            "dominance": obj.get("dominance"),
            "hotkey": Key.from_dict(obj.get("hotkey")) if obj.get("hotkey") is not None else None,
            "last_reward_block": obj.get("last_reward_block"),
            "name": obj.get("name"),
            "nominator_return_per_k": obj.get("nominator_return_per_k"),
            "nominator_return_per_k_30_day_average": obj.get("nominator_return_per_k_30_day_average"),
            "nominator_return_per_k_7_day_average": obj.get("nominator_return_per_k_7_day_average"),
            "nominators": obj.get("nominators"),
            "nominators_24_hr_change": obj.get("nominators_24_hr_change"),
            "pending_emission": obj.get("pending_emission"),
            "permits": obj.get("permits"),
            "rank": obj.get("rank"),
            "registrations": obj.get("registrations"),
            "stake": obj.get("stake"),
            "stake_24_hr_change": obj.get("stake_24_hr_change"),
            "subnet_dominance": [SubnetDominance.from_dict(_item) for _item in obj.get("subnet_dominance")] if obj.get("subnet_dominance") is not None else None,
            "system_stake": obj.get("system_stake"),
            "take": obj.get("take"),
            "timestamp": obj.get("timestamp"),
            "total_daily_return": obj.get("total_daily_return"),
            "validator_return": obj.get("validator_return"),
            "validator_stake": obj.get("validator_stake")
        })
        return _obj


